//! The Recovery Kit (SPEC §5 "Unlockers"; the encoding is in
//! docs/CRYPTO.md).
//!
//! A kit is 128 bits from the OS CSPRNG, generated by EnvCloak and never
//! chosen by the user. Its unlocker envelope's KEK is Argon2id of the 16
//! raw bytes. The user sees it once, as 28 Crockford base32 symbols in
//! seven groups of four:
//! - the first 26 symbols carry the 128 bits, most significant first, and
//!   the last two bits of the 26th are zero;
//! - the last 2 are check symbols of a Reed-Solomon code over GF(32), so
//!   any one or two wrong symbols, two swapped symbols included, are caught
//!   by [`RecoveryKit::parse`] before any key derivation runs.
//!
//! Parsing ignores case, hyphens and whitespace, and reads `O` as 0 and
//! `I` and `L` as 1, as Crockford's alphabet does. Errors ([`KitError`])
//! carry no part of the input.
//!
//! The kit's text is built in a [`Zeroizing`] string of exact capacity and
//! is never written anywhere by this crate; the CLI shows it on the
//! terminal or writes it to a file descriptor the user named, never to
//! stdout. This file is on security/expose-allowlist.txt: it reads the kit
//! to encode it and reads typed input to decode it.

use secrecy::ExposeSecret;
use zeroize::{Zeroize, Zeroizing};

use crate::crypto::fill_random_or_panic;
use crate::secret::SecretBytes;

/// Crockford's base32 alphabet: digits and letters without I, L, O and U.
const ALPHABET: &[u8; 32] = b"0123456789ABCDEFGHJKMNPQRSTVWXYZ";

/// A Recovery Kit: 128 random bits. It has no `Clone` or `Display`, and its
/// `Debug` prints `RecoveryKit(..)`.
pub struct RecoveryKit(SecretBytes);

impl RecoveryKit {
    /// The kit's size in bytes.
    pub const BYTES: usize = 16;
    /// Symbols in the kit's text, not counting hyphens.
    pub const SYMBOLS: usize = 28;
    /// Symbols that carry the 128 bits.
    const DATA_SYMBOLS: usize = 26;
    /// Symbols per group in [`RecoveryKit::to_display`].
    const GROUP: usize = 4;

    /// A new kit from the OS CSPRNG.
    ///
    /// # Panics
    /// When the OS random number generator fails.
    pub fn generate() -> Self {
        // Exact capacity, so `from_vec` keeps the allocation.
        let mut v = vec![0u8; Self::BYTES];
        fill_random_or_panic(&mut v);
        RecoveryKit(SecretBytes::from_vec(v))
    }

    /// Test support only (feature `testing`): the kit whose secret is the
    /// 16 bytes `b`, for fixtures whose kit is derived at run time.
    #[cfg(feature = "testing")]
    pub fn from_bytes_for_testing(b: &[u8]) -> Option<Self> {
        (b.len() == Self::BYTES).then(|| RecoveryKit(SecretBytes::copy_from(b)))
    }

    /// The kit as the user writes it down: seven groups of four symbols
    /// joined by hyphens, such as `ABCD-EFGH-...`.
    #[allow(clippy::disallowed_methods)] // Encodes the kit for display.
    pub fn to_display(&self) -> Zeroizing<String> {
        let mut symbols = Zeroizing::new([0u8; Self::SYMBOLS]);
        encode_bits(self.0.expose_secret(), &mut symbols[..Self::DATA_SYMBOLS]);
        let (c0, c1) = check_symbols(&symbols[..Self::DATA_SYMBOLS]);
        symbols[Self::DATA_SYMBOLS] = c0;
        symbols[Self::DATA_SYMBOLS + 1] = c1;
        let groups = Self::SYMBOLS / Self::GROUP;
        let mut out = Zeroizing::new(String::with_capacity(Self::SYMBOLS + groups - 1));
        for (i, s) in symbols.iter().enumerate() {
            if i > 0 && i % Self::GROUP == 0 {
                out.push('-');
            }
            out.push(char::from(ALPHABET[usize::from(*s)]));
        }
        debug_assert_eq!(out.len(), out.capacity());
        out
    }

    /// Parses a kit as typed or read from a file descriptor. Letters may be
    /// in either case; hyphens and whitespace are ignored.
    #[allow(clippy::disallowed_methods)] // Decodes the typed kit.
    pub fn parse(s: &SecretBytes) -> Result<Self, KitError> {
        let mut symbols = Zeroizing::new([0u8; Self::SYMBOLS]);
        let mut n = 0;
        for &b in s.expose_secret() {
            if matches!(b, b'-' | b' ' | b'\t' | b'\r' | b'\n') {
                continue;
            }
            let v = symbol_value(b).ok_or(KitError::Character)?;
            if n == Self::SYMBOLS {
                return Err(KitError::Length);
            }
            symbols[n] = v;
            n += 1;
        }
        if n != Self::SYMBOLS {
            return Err(KitError::Length);
        }
        if syndromes(&symbols[..]) != (0, 0) {
            return Err(KitError::Checksum);
        }
        let mut bytes = vec![0u8; Self::BYTES];
        if !decode_bits(&symbols[..Self::DATA_SYMBOLS], &mut bytes) {
            bytes.zeroize();
            return Err(KitError::Checksum);
        }
        Ok(RecoveryKit(SecretBytes::from_vec(bytes)))
    }

    /// The 16 raw bytes, the secret the kit's envelope is wrapped under.
    pub(crate) fn secret(&self) -> &SecretBytes {
        &self.0
    }
}

impl core::fmt::Debug for RecoveryKit {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str("RecoveryKit(..)")
    }
}

/// Why text is not a Recovery Kit. Carries no part of the input.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum KitError {
    /// Not 28 letters and digits.
    Length,
    /// A character other than a letter, a digit, a hyphen or whitespace,
    /// or the letter U.
    Character,
    /// The check symbols do not match: something is mistyped.
    Checksum,
}

impl KitError {
    /// Every kind, in declaration order.
    pub const ALL: [KitError; 3] = [KitError::Length, KitError::Character, KitError::Checksum];

    /// The fixed message for this error.
    pub const fn message(self) -> &'static str {
        match self {
            KitError::Length => "a Recovery Kit has 28 letters and digits, in seven groups of four",
            KitError::Character => "a Recovery Kit holds only letters, digits and hyphens",
            KitError::Checksum => {
                "the Recovery Kit does not check: a letter or digit is mistyped or out of order"
            }
        }
    }
}

impl core::fmt::Display for KitError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.message())
    }
}

impl std::error::Error for KitError {}

/// A symbol's value, reading `O` as 0 and `I` and `L` as 1; `None` for
/// anything outside Crockford's alphabet (U included).
fn symbol_value(b: u8) -> Option<u8> {
    let b = match b.to_ascii_uppercase() {
        b'O' => b'0',
        b'I' | b'L' => b'1',
        b'U' => return None,
        other => other,
    };
    ALPHABET
        .iter()
        .position(|a| *a == b)
        .and_then(|p| u8::try_from(p).ok())
}

/// Bit `i` of `bytes`, most significant first; 0 past the end.
fn bit(bytes: &[u8], i: usize) -> u8 {
    bytes.get(i / 8).map_or(0, |b| (b >> (7 - i % 8)) & 1)
}

/// Splits `bytes` into 5-bit symbols, most significant first, padding the
/// last one with zero bits.
fn encode_bits(bytes: &[u8], out: &mut [u8]) {
    for (j, s) in out.iter_mut().enumerate() {
        *s = (0..5).fold(0, |acc, k| (acc << 1) | bit(bytes, 5 * j + k));
    }
}

/// The inverse of [`encode_bits`]. Returns false when a padding bit is set.
fn decode_bits(symbols: &[u8], out: &mut [u8]) -> bool {
    let bits = out.len() * 8;
    let mut pad = 0u8;
    for (j, s) in symbols.iter().enumerate() {
        for k in 0..5 {
            let i = 5 * j + k;
            let b = (s >> (4 - k)) & 1;
            if i < bits {
                out[i / 8] |= b << (7 - i % 8);
            } else {
                pad |= b;
            }
        }
    }
    pad == 0
}

// GF(32) with the primitive polynomial x^5 + x^2 + 1; alpha = x = 2.
const GF_POLY: u8 = 0b10_0101;

fn gf_mul(mut a: u8, mut b: u8) -> u8 {
    let mut p = 0;
    for _ in 0..5 {
        if b & 1 != 0 {
            p ^= a;
        }
        b >>= 1;
        a <<= 1;
        if a & 0x20 != 0 {
            a ^= GF_POLY;
        }
    }
    p
}

/// alpha to the power `i`.
fn gf_alpha(i: usize) -> u8 {
    (0..i).fold(1, |x, _| gf_mul(x, 2))
}

/// The multiplicative inverse of a nonzero element: a^30, as a^31 = 1.
fn gf_inv(a: u8) -> u8 {
    (0..30).fold(1, |x, _| gf_mul(x, a))
}

/// The two syndromes of a codeword: the sum of its symbols, and the sum of
/// symbol `i` times alpha^i. Both are zero for a valid kit. Any one or two
/// changed symbols make one of them nonzero: the columns (1, alpha^i) of
/// the check matrix are pairwise independent while alpha^i are distinct,
/// which holds for up to 31 symbols.
fn syndromes(symbols: &[u8]) -> (u8, u8) {
    symbols.iter().enumerate().fold((0, 0), |(s0, s1), (i, s)| {
        (s0 ^ s, s1 ^ gf_mul(gf_alpha(i), *s))
    })
}

/// The two check symbols that follow `data` (26 symbols): the values of
/// positions 26 and 27 that make both syndromes zero.
fn check_symbols(data: &[u8]) -> (u8, u8) {
    let n = data.len();
    let (a, b) = syndromes(data);
    let (w0, w1) = (gf_alpha(n), gf_alpha(n + 1));
    // c0 + c1 = a and w0 c0 + w1 c1 = b, so c0 = (b + w1 a) / (w0 + w1).
    let c0 = gf_mul(b ^ gf_mul(w1, a), gf_inv(w0 ^ w1));
    (c0, a ^ c0)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn alpha_generates_the_field() {
        let powers: std::collections::BTreeSet<u8> = (0..31).map(gf_alpha).collect();
        assert_eq!(powers.len(), 31);
        assert!(!powers.contains(&0));
        assert_eq!(gf_alpha(31), 1);
        for a in 1..32 {
            assert_eq!(gf_mul(a, gf_inv(a)), 1, "{a}");
        }
    }

    #[test]
    fn check_symbols_zero_the_syndromes() {
        for seed in 0u8..=255 {
            let data: Vec<u8> = (0..26u8)
                .map(|i| (seed.wrapping_mul(7) ^ i.wrapping_mul(13)) % 32)
                .collect();
            let (c0, c1) = check_symbols(&data);
            let mut word = data.clone();
            word.extend([c0, c1]);
            assert_eq!(syndromes(&word), (0, 0));
        }
    }

    #[test]
    fn bits_round_trip_and_padding_is_checked() {
        let bytes: Vec<u8> = (0..16u8).map(|i| i.wrapping_mul(37) ^ 0xa5).collect();
        let mut symbols = [0u8; 26];
        encode_bits(&bytes, &mut symbols);
        assert!(symbols.iter().all(|s| *s < 32));
        let mut back = [0u8; 16];
        assert!(decode_bits(&symbols, &mut back));
        assert_eq!(back[..], bytes[..]);
        symbols[25] |= 1;
        let mut back = [0u8; 16];
        assert!(!decode_bits(&symbols, &mut back));
    }

    #[test]
    fn crockford_aliases() {
        assert_eq!(symbol_value(b'o'), Some(0));
        assert_eq!(symbol_value(b'O'), Some(0));
        assert_eq!(symbol_value(b'i'), Some(1));
        assert_eq!(symbol_value(b'L'), Some(1));
        assert_eq!(symbol_value(b'z'), Some(31));
        assert_eq!(symbol_value(b'u'), None);
        assert_eq!(symbol_value(b'*'), None);
    }
}
