//! Redaction of output produced by real serializers and URL encoders.
//!
//! Fixtures are generated by `tests/fixtures/generate.sh` with the actual
//! runtimes (Python, Node, Go, .NET, Ruby) and loaded here as bytes. Each
//! fixture is first decoded and checked against the known value, so a
//! corrupted or hand-edited fixture fails loudly instead of testing nothing.
#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::path::{Path, PathBuf};

use envcloak_redact::RedactorBuilder;

/// The JSON fixture value: every JSON escape class.
const JSON_VALUE: &str = "ab/cd\"ef\\gh\u{8}ij\u{e9}kl\u{1F600}mn+op qr'st<uv";
/// The URL fixture value: reserved characters, a space and non-ASCII.
const URL_VALUE: &str = "tok/en+val ue~!*'()&=x\u{e9}";

fn fixtures(kind: &str) -> Vec<PathBuf> {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(kind);
    let mut files: Vec<PathBuf> = std::fs::read_dir(&dir)
        .expect("fixture dir")
        .map(|e| e.unwrap().path())
        .collect();
    files.sort();
    assert!(!files.is_empty(), "no fixtures in {}", dir.display());
    files
}

fn name(p: &Path) -> String {
    p.file_name().unwrap().to_string_lossy().into_owned()
}

#[test]
fn every_generated_json_fixture_is_redacted_completely() {
    let (r, _) = RedactorBuilder::new().secret("t", JSON_VALUE).build();
    for path in fixtures("json") {
        let bytes = std::fs::read(&path).unwrap();
        let decoded: String = serde_json::from_slice(&bytes).expect("fixture is valid JSON");
        assert_eq!(
            decoded,
            JSON_VALUE,
            "{} does not decode to the value",
            name(&path)
        );
        let out = r.redact(&bytes);
        assert_eq!(
            String::from_utf8(out).unwrap(),
            "\"[envcloak:t]\"",
            "{} was not fully redacted",
            name(&path)
        );
    }
}

#[test]
fn json_fixture_set_covers_the_expected_runtimes() {
    let names: Vec<String> = fixtures("json").iter().map(|p| name(p)).collect();
    for runtime in [
        "python_ensure_ascii",
        "python_utf8",
        "node",
        "go",
        "dotnet",
        "ruby",
    ] {
        assert!(
            names.iter().any(|n| n.starts_with(runtime)),
            "missing JSON fixture for {runtime}; run tests/fixtures/generate.sh"
        );
    }
}

/// Decodes percent escapes; `+` means space only for form-style encoders.
fn percent_decode(s: &[u8], plus_is_space: bool) -> Vec<u8> {
    let hex = |c: u8| (c as char).to_digit(16).expect("hex digit") as u8;
    let mut out = Vec::new();
    let mut i = 0;
    while i < s.len() {
        match s[i] {
            b'%' => {
                out.push(hex(s[i + 1]) << 4 | hex(s[i + 2]));
                i += 3;
            }
            b'+' if plus_is_space => {
                out.push(b' ');
                i += 1;
            }
            b => {
                out.push(b);
                i += 1;
            }
        }
    }
    out
}

fn is_form_style(file: &str) -> bool {
    [
        "plus",
        "URLSearchParams",
        "QueryEscape",
        "UrlEncode",
        "CGI",
        "www_form",
    ]
    .iter()
    .any(|m| file.contains(m))
}

fn lower_hex_escapes(s: &[u8]) -> Vec<u8> {
    let mut out = s.to_vec();
    let mut i = 0;
    while i + 2 < out.len() {
        if out[i] == b'%' {
            out[i + 1] = out[i + 1].to_ascii_lowercase();
            out[i + 2] = out[i + 2].to_ascii_lowercase();
            i += 3;
        } else {
            i += 1;
        }
    }
    out
}

#[test]
fn every_generated_url_fixture_is_redacted_in_both_hex_cases() {
    let (r, _) = RedactorBuilder::new().secret("u", URL_VALUE).build();
    for path in fixtures("url") {
        let file = name(&path);
        let bytes = std::fs::read(&path).unwrap();
        assert_eq!(
            percent_decode(&bytes, is_form_style(&file)),
            URL_VALUE.as_bytes(),
            "{file} does not decode to the value"
        );
        for (case, input) in [
            ("as generated", bytes.clone()),
            ("lowercase hex", lower_hex_escapes(&bytes)),
        ] {
            let out = r.redact(&input);
            assert_eq!(
                String::from_utf8(out).unwrap(),
                "[envcloak:u]",
                "{file} ({case}) was not fully redacted"
            );
        }
    }
}

#[test]
fn url_fixture_set_covers_the_expected_runtimes() {
    let names: Vec<String> = fixtures("url").iter().map(|p| name(p)).collect();
    for runtime in ["python", "node", "go", "dotnet", "ruby"] {
        assert!(
            names.iter().any(|n| n.starts_with(runtime)),
            "missing URL fixture for {runtime}; run tests/fixtures/generate.sh"
        );
    }
}
