[package]
name = "envcloak"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
envcloak-sys.workspace = true

[dev-dependencies]
envcloak-sys = { workspace = true, features = ["testing"] }
envcloak-testkit.workspace = true
