//! The provider registry as compiled in: every `providers/*.toml` file and
//! `providers/multi-tenant-suffixes.txt`, byte for byte (SPEC §8 "Registry
//! safety"). [`crate::load_embedded`] parses and checks them.
//!
//! Generated by scripts/gen-providers.py from providers/. Do not edit.

/// Each file as `(file name, contents)`, sorted by file name.
pub(crate) static FILES: &[(&str, &str)] = &[
    (
        "anthropic.toml",
        r#"# Anthropic. Format and loader rules: docs/PROVIDERS.md.
id = "anthropic"
name = "Anthropic"

# API keys (`sk-ant-api03-`), Admin API keys (`sk-ant-admin01-`) and OAuth
# tokens: `sk-ant-`, a kind and a two-digit version, then the key.
key_patterns = ['^sk-ant-[a-z]{2,10}[0-9]{2}-[A-Za-z0-9_-]{20,}$']
# Anthropic has no test mode: every key acts on the real account.
live_patterns = ['^sk-ant-']
env_hints = ["ANTHROPIC_API_KEY", "ANTHROPIC_ADMIN_KEY", "CLAUDE_API_KEY"]

allowed_hosts = ["api.anthropic.com"]
auth = [{ header = "x-api-key" }]
# The Admin API: API keys, workspaces, members and invites.
denied_paths = ["/v1/organizations"]

[links]
docs = "https://docs.anthropic.com/en/api/overview"
billing = "https://console.anthropic.com/settings/billing"
keys = "https://console.anthropic.com/settings/keys"
dashboard = "https://console.anthropic.com/usage"
"#,
    ),
    (
        "aws.toml",
        r#"# Amazon Web Services. Format and loader rules: docs/PROVIDERS.md.
id = "aws"
name = "AWS"

# Access key ids: long-term (`AKIA`) and temporary (`ASIA`). The secret
# access key has no shape of its own to detect.
key_patterns = ['^(?:AKIA|ASIA)[A-Z2-7]{16}$']
# AWS has no test mode: every key acts on the real account.
live_patterns = ['^(?:AKIA|ASIA)']
env_hints = ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_SESSION_TOKEN"]

# No hosts and no auth slots: AWS signs requests with SigV4, which proxy mode
# does not support (SPEC §6.2); use the native credential helper. A wildcard
# such as *.amazonaws.com would be refused anyway: it is a multi-tenant
# suffix.
allowed_hosts = []

[links]
docs = "https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html"
billing = "https://console.aws.amazon.com/billing/home"
keys = "https://console.aws.amazon.com/iam/home#/security_credentials"
"#,
    ),
    (
        "deepseek.toml",
        r#"# DeepSeek. Format and loader rules: docs/PROVIDERS.md.
id = "deepseek"
name = "DeepSeek"

# `sk-` and 32 lowercase hex digits. OpenAI's older user-key pattern also
# matches this shape, so detection goes by the variable name when both do.
key_patterns = ['^sk-[a-f0-9]{32}$']
# DeepSeek has no test mode: every key acts on the real account.
live_patterns = ['^sk-']
env_hints = ["DEEPSEEK_API_KEY"]

allowed_hosts = ["api.deepseek.com"]
auth = [{ header = "authorization", scheme = "Bearer" }]

[links]
docs = "https://api-docs.deepseek.com"
billing = "https://platform.deepseek.com/usage"
keys = "https://platform.deepseek.com/api_keys"

# Balance adapter (M4 polls it). Its request may go only to an allowed host,
# over HTTPS, with the key in a declared auth slot.
[balance]
request = { method = "GET", url = "https://api.deepseek.com/user/balance", auth = "bearer" }
value = "$.balance_infos[0].total_balance"
currency = "$.balance_infos[0].currency"
"#,
    ),
    (
        "github.toml",
        r#"# GitHub. Format and loader rules: docs/PROVIDERS.md.
id = "github"
name = "GitHub"

# Classic personal access tokens (`ghp_`), OAuth (`gho_`), user-to-server
# (`ghu_`), server-to-server (`ghs_`) and refresh (`ghr_`) tokens, and
# fine-grained personal access tokens (`github_pat_`).
key_patterns = [
  '^gh[pousr]_[A-Za-z0-9]{36,251}$',
  '^github_pat_[A-Za-z0-9_]{36,244}$',
]
# GitHub has no test mode: every token acts on real repositories.
live_patterns = ['^gh[pousr]_', '^github_pat_']
env_hints = ["GITHUB_TOKEN", "GH_TOKEN", "GITHUB_PAT", "GITHUB_PERSONAL_ACCESS_TOKEN"]

allowed_hosts = ["api.github.com", "uploads.github.com"]
auth = [
  { header = "authorization", scheme = "Bearer" },
  { header = "authorization", scheme = "token" },
]
# Endpoints that manage or mint credentials: OAuth authorizations and
# applications, GitHub App installation tokens, SSH, GPG and deploy keys,
# Actions, Codespaces and Dependabot secrets (user, repository,
# environment and organization), organization private registries,
# runner registration and removal tokens (repository, organization and
# enterprise), organization token policies and SSO credential
# authorizations; and site administration.
denied_paths = [
  "/authorizations",
  "/applications",
  "/app",
  "/admin",
  "/user/keys",
  "/user/gpg_keys",
  "/user/ssh_signing_keys",
  "/user/codespaces/secrets",
  "/repos/*/*/keys",
  "/repos/*/*/actions/secrets",
  "/repos/*/*/actions/runners",
  "/repos/*/*/codespaces/secrets",
  "/repos/*/*/dependabot/secrets",
  "/repos/*/*/environments/*/secrets",
  "/orgs/*/actions/secrets",
  "/orgs/*/actions/runners",
  "/orgs/*/codespaces/secrets",
  "/orgs/*/dependabot/secrets",
  "/orgs/*/private-registries",
  "/orgs/*/credential-authorizations",
  "/orgs/*/personal-access-tokens",
  "/orgs/*/personal-access-token-requests",
  "/enterprises/*/actions/runners",
]

[links]
docs = "https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens"
billing = "https://github.com/settings/billing"
keys = "https://github.com/settings/tokens"
"#,
    ),
    (
        "multi-tenant-suffixes.txt",
        r#"# Domains under which many unrelated parties get hosts of their own. The
# registry loader refuses a wildcard allowed host (`*.<domain>`) whose domain
# is one of these, is under one, or is above one: the key could then be sent
# to a host anyone can create. A tenant's own host, such as acme.supabase.co,
# is stored on the item instead (SPEC §8 "Registry safety"). One domain per
# line, lowercase; `#` starts a comment. Format: docs/PROVIDERS.md.
#
# The list is kept by hand, so a wildcard over a platform it misses would
# load: no shipped provider uses a wildcard, and adding one needs a check
# against the Public Suffix List in review.

# Application and function hosting
supabase.co
supabase.in
workers.dev
pages.dev
r2.dev
trycloudflare.com
vercel.app
vercel.dev
now.sh
herokuapp.com
herokudns.com
netlify.app
netlify.com
fly.dev
onrender.com
railway.app
deno.dev
deno.net
glitch.me
repl.co
replit.app
replit.dev
surge.sh
pythonanywhere.com
modal.run
hf.space
ngrok.io
ngrok.app
ngrok-free.app
loca.lt
ngrok.dev
ngrok-free.dev
amplifyapp.com
elasticbeanstalk.com
azurecontainerapps.io
csb.app
codesandbox.io
stackblitz.io
webcontainer.io
gitpod.io
github.dev
koyeb.app
streamlit.app
lovable.app
val.run
webflow.io
wixsite.com
myshopify.com
blogspot.com
ts.net

# Cloud platforms: storage buckets, functions, API gateways and customer
# resources such as <resource>.openai.azure.com
amazonaws.com
cloudfront.net
awsapps.com
on.aws
azure.com
azurewebsites.net
azure-api.net
azurestaticapps.net
azureedge.net
cloudapp.net
windows.net
googleapis.com
googleusercontent.com
appspot.com
run.app
cloudfunctions.net
web.app
firebaseapp.com
firebaseio.com
digitaloceanspaces.com
ondigitalocean.app
linodeobjects.com
azurefd.net
azurecr.io
firebasestorage.app
cloudflarestorage.com
aliyuncs.com
myqcloud.com
oraclecloud.com
backblazeb2.com
wasabisys.com

# Code and page hosting
github.io
githubusercontent.com
gitlab.io
bitbucket.io
codeberg.page

# Public suffixes of two labels, under which anyone can register a domain.
# The loader also refuses a wildcard over any two-label domain whose first
# label is a public second-level label (co, com, net, org, ac, ...), so these
# are listed to refuse wildcards under them too.
co.uk
org.uk
com.au
net.au
org.au
co.nz
co.jp
com.br
com.cn
co.in
co.za
com.mx
"#,
    ),
    (
        "openai.toml",
        r#"# OpenAI. Format and loader rules: docs/PROVIDERS.md.
id = "openai"
name = "OpenAI"

# Project, service-account, admin and user keys. The last pattern is the
# older user-key shape: `sk-` and letters and digits only. Keys of
# OpenAI-compatible providers can share it (DeepSeek's do), so when both
# match, detection goes by the variable name.
key_patterns = [
  '^sk-(?:proj|svcacct|admin|None)-[A-Za-z0-9_-]{20,}$',
  '^sk-[A-Za-z0-9]{32,}$',
]
# OpenAI has no test mode: every key acts on the real account.
live_patterns = ['^sk-']
env_hints = ["OPENAI_API_KEY", "OPENAI_ADMIN_KEY"]

allowed_hosts = ["api.openai.com"]
auth = [{ header = "authorization", scheme = "Bearer" }]
# The Admin API (admin keys, project API keys, service accounts, users and
# invites) and every Realtime route that exchanges the key for a client
# secret a browser or another process could then use.
denied_paths = [
  "/v1/organization",
  "/v1/realtime/client_secrets",
  "/v1/realtime/translations/client_secrets",
  "/v1/realtime/sessions",
  "/v1/realtime/transcription_sessions",
]

[links]
docs = "https://platform.openai.com/docs/api-reference/authentication"
billing = "https://platform.openai.com/settings/organization/billing/overview"
keys = "https://platform.openai.com/api-keys"
dashboard = "https://platform.openai.com/usage"
"#,
    ),
    (
        "stripe.toml",
        r#"# Stripe. Format and loader rules: docs/PROVIDERS.md.
id = "stripe"
name = "Stripe"

# Secret (`sk_`), restricted (`rk_`) and publishable (`pk_`) keys, each in
# live or test mode, and webhook signing secrets.
key_patterns = [
  '^[rsp]k_(?:live|test)_[0-9A-Za-z]{10,247}$',
  '^whsec_[0-9A-Za-z+/=]{20,}$',
]
live_patterns = ['^[rsp]k_live_']
test_patterns = ['^[rsp]k_test_']
env_hints = [
  "STRIPE_SECRET_KEY",
  "STRIPE_API_KEY",
  "STRIPE_RESTRICTED_KEY",
  "STRIPE_PUBLISHABLE_KEY",
  "STRIPE_WEBHOOK_SECRET",
]

allowed_hosts = ["api.stripe.com", "files.stripe.com"]
# Stripe takes the key as a bearer token or as the Basic auth user name.
auth = [
  { header = "authorization", scheme = "Bearer" },
  { basic = "user" },
]
# Endpoints that mint credentials or hand out account access: ephemeral
# keys, Connect account links, sessions and accounts (with their login
# links), app secrets, webhook endpoints (creating one returns its signing
# secret), Terminal connection tokens and Issuing (card numbers).
denied_paths = [
  "/v1/ephemeral_keys",
  "/v1/account_links",
  "/v1/account_sessions",
  "/v1/accounts",
  "/v1/apps/secrets",
  "/v1/webhook_endpoints",
  "/v1/terminal/connection_tokens",
  "/v1/issuing",
]

[links]
docs = "https://docs.stripe.com/keys"
billing = "https://dashboard.stripe.com/settings/billing"
keys = "https://dashboard.stripe.com/apikeys"
dashboard = "https://dashboard.stripe.com/"
"#,
    ),
];
