//! EnvCloak's provider registry (SPEC §8, §6.3): which provider a key
//! belongs to, whether it is a test or live key, where its docs, billing
//! and key pages are, which hosts it may be sent to and in which auth slot,
//! and how its balance is read.
//!
//! - [`load_embedded`]: the registry compiled into the release from
//!   `providers/*.toml` and `providers/multi-tenant-suffixes.txt`
//!   (`embedded.rs`, generated by scripts/gen-providers.py). Nothing reads
//!   a registry from disk or the network; local overrides are M2+ and need
//!   an approval proof.
//! - The loader's rules, each a [`RegistryErrorKind`] with a file and a
//!   line (gate 18): every URL is `https://`; a request goes only to an
//!   allowed host, with the key in a declared auth slot; no wildcard host
//!   is under or over a multi-tenant suffix, or over a public suffix, and
//!   in M1 no other wildcard host loads either (no Public Suffix List is
//!   embedded yet); key
//!   patterns match whole values of at least 16 bytes, start with a
//!   literal of at least 3 bytes and keep no captures. One bad file fails
//!   the whole registry.
//! - [`Registry::detect`]: a value's provider and classification, with the
//!   variable name breaking ties. It returns ids only, never the value.
//! - [`Registry::prefill`]: a new item's provider, links, allowed hosts and
//!   classification from a detection.
//!
//! The format is in docs/PROVIDERS.md.

mod detect;
mod embedded;
mod error;
mod registry;
mod safety;

pub use detect::{
    Detection, MAX_PASSWORD_READINGS, PasswordForm, SECRET_RUN, password_chars,
    password_form_chars, shaped_like_secret,
};
pub use error::{RegistryError, RegistryErrorKind};
#[cfg(feature = "testing")]
pub use registry::load_from;
pub use registry::{
    Adapter, KeyPattern, MAX_FILE, Method, Provider, ProviderId, Registry, Request, SUFFIX_FILE,
    embedded_files, load_embedded,
};
pub use safety::{
    AuthSlot, HostPattern, HttpsUrl, JsonPath, MAX_PATTERN, MIN_KEY_LEN, MIN_KEY_PREFIX,
    PathSegment,
};
