#!/usr/bin/env python3
"""Generates the two word lists that crates/envcloak-core compiles in
(SPEC §5 "Unlockers": passphrase rules and the suggested passphrase):

- crates/envcloak-core/src/wordlists/eff_large.rs: the EFF Large Wordlist
  for Passphrases (7,776 words), word for word, as an array: a suggested
  passphrase picks its words by secret indexes, and an array reads the
  `i`th word in the same time whatever `i` is, where scanning a text for
  its `i`th line takes time in proportion to `i`;
- crates/envcloak-core/src/wordlists/common_passwords.rs: every password of
  12 or more characters in the Pwdb-Public top 1,000,000 list, as SecLists
  redistributes it, lowercased, deduplicated and sorted.

The lists are Rust source, not text files the crate includes, because
scripts/check-sources.sh accepts no compiled input other than the Rust files
scripts/check-unsafe.sh reads. Sources and licenses are in
THIRD_PARTY_NOTICES.md. Each input must match the SHA-256 below, so the
output is reproducible; `wordlists` tests in envcloak-core check the
invariants and rebuild the EFF file's digest from the compiled list, and
envcloak-core does not build unless the EFF list is an array of 7,776
words.

Download the inputs, then run this from the repository root:

    curl -fLo eff_large_wordlist.txt \\
      https://www.eff.org/files/2016/07/18/eff_large_wordlist.txt
    curl -fLo Pwdb_top-1000000.txt \\
      https://raw.githubusercontent.com/danielmiessler/SecLists/12274c98fdebe98c7a7284914436a472ed469aed/Passwords/Common-Credentials/Pwdb_top-1000000.txt
    python3 scripts/gen-wordlists.py eff_large_wordlist.txt Pwdb_top-1000000.txt
"""

import hashlib
import os
import sys

EFF_SHA256 = "addd35536511597a02fa0a9ff1e5284677b8883b83e986e43f15a3db996b903e"
PWDB_SHA256 = "e9a88f67aafe65496682dc374559ee714e978bee50314767494c3e37a18c9fc8"
MIN_CHARS = 12
OUT_DIR = os.path.join("crates", "envcloak-core", "src", "wordlists")


def read_checked(path, want):
    with open(path, "rb") as f:
        data = f.read()
    got = hashlib.sha256(data).hexdigest()
    if got != want:
        sys.exit("%s: SHA-256 %s, expected %s" % (path, got, want))
    return data


def array(words):
    """A Rust array literal of string literals, one per line. Only `"` and
    `\\` need escaping: every word is printable ASCII."""
    out = ["[\n"]
    for word in words:
        assert all(0x20 <= ord(c) <= 0x7E for c in word), word
        out.append('    "' + word.replace("\\", "\\\\").replace('"', '\\"') + '",\n')
    out.append("]")
    return "".join(out)


def literal(lines):
    """A Rust string literal holding `lines`, one per line, each followed by
    a newline. Only `"` and `\\` need escaping: every line is printable
    ASCII."""
    # The first line follows a line continuation, which would drop its
    # leading whitespace.
    assert lines and not lines[0][:1].isspace()
    out = ['"\\\n']
    for line in lines:
        assert all(0x20 <= ord(c) <= 0x7E for c in line), line
        out.append(line.replace("\\", "\\\\").replace('"', '\\"') + "\n")
    out.append('"')
    return "".join(out)


def eff_words(data):
    words = []
    for n, line in enumerate(data.decode("ascii").splitlines()):
        dice, word = line.split("\t")
        # Five dice, 11111 to 66666, in order.
        want = "".join(str(1 + (n // 6 ** (4 - i)) % 6) for i in range(5))
        if dice != want:
            sys.exit("EFF list line %d: dice %s, expected %s" % (n + 1, dice, want))
        words.append(word)
    if len(words) != 7776 or len(set(words)) != 7776:
        sys.exit("EFF list: expected 7776 distinct words")
    return words


def common_passwords(data):
    keep = set()
    for line in data.decode("utf-8").split("\n"):
        line = line.rstrip("\r")
        if len(line) >= MIN_CHARS and all(0x20 <= ord(c) <= 0x7E for c in line):
            keep.add(line.lower())
    return sorted(keep)


EFF_HEADER = """\
//! The EFF Large Wordlist for Passphrases, word for word, in order: the
//! words of a suggested passphrase (SPEC §5 "Unlockers").
//!
//! Source: the Electronic Frontier Foundation,
//! <https://www.eff.org/dice>, file
//! <https://www.eff.org/files/2016/07/18/eff_large_wordlist.txt>
//! (SHA-256 {sha}).
//! License: Creative Commons Attribution 3.0 United States (CC BY 3.0 US),
//! <https://creativecommons.org/licenses/by/3.0/us/>. The upstream file
//! pairs each word with its five dice rolls; only the words are kept here.
//! See THIRD_PARTY_NOTICES.md.
//!
//! Generated by scripts/gen-wordlists.py. Do not edit.

/// The 7,776 words in the upstream order (dice 11111 to 66666), read by
/// index.
pub(crate) static EFF_LARGE: [&str; {count}] = {lit};
"""

COMMON_HEADER = """\
//! Common passwords of {min} or more characters: a passphrase on this list
//! is refused (SPEC §5 "Unlockers").
//!
//! Source: the Pwdb-Public top 1,000,000 passwords, copyright (c) 2020 Ata
//! Hakçıl, as redistributed in SecLists, copyright (c) 2018 Daniel
//! Miessler: <https://github.com/danielmiessler/SecLists/blob/12274c98fdebe98c7a7284914436a472ed469aed/Passwords/Common-Credentials/Pwdb_top-1000000.txt>
//! (SHA-256 {sha}).
//! Both are under the MIT License, whose text is in
//! THIRD_PARTY_NOTICES.md.
//!
//! Kept: every entry of {min} or more characters that is printable ASCII,
//! lowercased, without duplicates, sorted by byte. Shorter entries are
//! refused by the length rule anyway.
//!
//! Generated by scripts/gen-wordlists.py. Do not edit.

/// One password per line, {count:,} lines.
pub(crate) static COMMON_PASSWORDS: &str = {lit};
"""


def write_eff(path):
    """Writes eff_large.rs from the upstream EFF file at `path`; returns the
    number of words."""
    eff = eff_words(read_checked(path, EFF_SHA256))
    with open(os.path.join(OUT_DIR, "eff_large.rs"), "w") as f:
        f.write(EFF_HEADER.format(sha=EFF_SHA256, count=len(eff), lit=array(eff)))
    return len(eff)


def write_common(path):
    """Writes common_passwords.rs from the Pwdb-Public file at `path`;
    returns the number of entries."""
    common = common_passwords(read_checked(path, PWDB_SHA256))
    with open(os.path.join(OUT_DIR, "common_passwords.rs"), "w") as f:
        f.write(
            COMMON_HEADER.format(
                min=MIN_CHARS, sha=PWDB_SHA256, count=len(common), lit=literal(common)
            )
        )
    return len(common)


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    eff = write_eff(sys.argv[1])
    common = write_common(sys.argv[2])
    print("eff_large.rs: %d words; common_passwords.rs: %d entries" % (eff, common))


if __name__ == "__main__":
    main()
