#!/usr/bin/env python3
"""Generates crates/envcloak-providers/src/embedded.rs, the provider registry
compiled into EnvCloak (SPEC §8 "Registry safety": registry files ship
inside the release and are never fetched at runtime).

It holds every providers/*.toml file and providers/multi-tenant-suffixes.txt
byte for byte, as raw Rust string literals. They are Rust source, not files
the crate includes, because scripts/check-sources.sh accepts no compiled
input other than the Rust files scripts/check-unsafe.sh reads, and
check-unsafe.sh refuses build scripts. The crate's `embedded` test fails
when the literals and the files in providers/ differ, so an edit that was
not regenerated fails CI. The loader's rules are in docs/PROVIDERS.md.

Run from the repository root after editing providers/:

    python3 scripts/gen-providers.py            # rewrite embedded.rs
    python3 scripts/gen-providers.py --check    # exit 1 if it is stale
"""

import os
import sys

SRC_DIR = "providers"
SUFFIXES = "multi-tenant-suffixes.txt"
OUT = os.path.join("crates", "envcloak-providers", "src", "embedded.rs")

HEADER = """\
//! The provider registry as compiled in: every `providers/*.toml` file and
//! `providers/multi-tenant-suffixes.txt`, byte for byte (SPEC §8 "Registry
//! safety"). [`crate::load_embedded`] parses and checks them.
//!
//! Generated by scripts/gen-providers.py from providers/. Do not edit.

/// Each file as `(file name, contents)`, sorted by file name.
pub(crate) static FILES: &[(&str, &str)] = &[
"""


def literal(text):
    """A raw Rust string literal whose value is `text`, with enough `#`s
    that no `"` in the text ends it. The files hold no control characters
    but newlines."""
    for n, line in enumerate(text.split("\n"), 1):
        for c in line:
            if ord(c) < 0x20 or ord(c) == 0x7F:
                sys.exit("line %d holds control character U+%04X" % (n, ord(c)))
    hashes = "#"
    while '"' + hashes in text:
        hashes += "#"
    return "r" + hashes + '"' + text + '"' + hashes


def files():
    names = sorted(
        n for n in os.listdir(SRC_DIR) if n.endswith(".toml") or n == SUFFIXES
    )
    if SUFFIXES not in names:
        sys.exit("%s/%s is missing" % (SRC_DIR, SUFFIXES))
    out = []
    for name in names:
        path = os.path.join(SRC_DIR, name)
        with open(path, "rb") as f:
            data = f.read()
        try:
            text = data.decode("utf-8")
        except UnicodeDecodeError:
            sys.exit("%s is not UTF-8" % path)
        if "\r" in text:
            sys.exit("%s: use LF line endings" % path)
        out.append((name, text))
    return out


def render():
    parts = [HEADER]
    for name, text in files():
        try:
            lit = literal(text)
        except SystemExit as e:
            sys.exit("%s/%s: %s" % (SRC_DIR, name, e.code))
        parts.append('    (\n        "%s",\n        %s,\n    ),\n' % (name, lit))
    parts.append("];\n")
    return "".join(parts)


def main():
    check = sys.argv[1:] == ["--check"]
    if sys.argv[1:] and not check:
        sys.exit("usage: gen-providers.py [--check]")
    want = render()
    if check:
        try:
            with open(OUT, encoding="utf-8") as f:
                have = f.read()
        except OSError:
            have = None
        if have != want:
            sys.exit("%s is stale: run python3 scripts/gen-providers.py" % OUT)
        return
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(want)


if __name__ == "__main__":
    main()
