#!/usr/bin/env python3
"""Generates crates/envcloak-policy/src/agents_builtin.rs, the agent catalog
compiled into EnvCloak (SPEC §10a; docs/AGENTS.md): integrations/agents.toml
byte for byte, as a raw Rust string literal.

It is Rust source, not a file the crate includes, because
scripts/check-sources.sh accepts no compiled input other than the Rust files
scripts/check-unsafe.sh reads, and check-unsafe.sh refuses build scripts.
The crate's `agents` test fails when the literal and the file differ, so an
edit that was not regenerated fails CI.

Run from the repository root after editing integrations/agents.toml:

    python3 scripts/gen-agents.py            # rewrite agents_builtin.rs
    python3 scripts/gen-agents.py --check    # exit 1 if it is stale
"""

import os
import sys

SRC = os.path.join("integrations", "agents.toml")
OUT = os.path.join("crates", "envcloak-policy", "src", "agents_builtin.rs")

HEADER = """\
//! The agent catalog as compiled in: integrations/agents.toml, byte for
//! byte (SPEC §10a). [`crate::AgentCatalog::builtin`] parses it.
//!
//! Generated by scripts/gen-agents.py from integrations/agents.toml. Do not
//! edit.

/// The contents of integrations/agents.toml.
pub(crate) static AGENTS_TOML: &str = """


def literal(text):
    """A raw Rust string literal whose value is `text`, with enough `#`s
    that no `"` in the text ends it. The file holds no control characters
    but newlines."""
    for n, line in enumerate(text.split("\n"), 1):
        for c in line:
            if ord(c) < 0x20 or ord(c) == 0x7F:
                sys.exit("line %d holds control character U+%04X" % (n, ord(c)))
    hashes = "#"
    while '"' + hashes in text:
        hashes += "#"
    return "r" + hashes + '"' + text + '"' + hashes


def render():
    with open(SRC, "rb") as f:
        data = f.read()
    try:
        text = data.decode("utf-8")
    except UnicodeDecodeError:
        sys.exit("%s is not UTF-8" % SRC)
    if "\r" in text:
        sys.exit("%s: use LF line endings" % SRC)
    try:
        lit = literal(text)
    except SystemExit as e:
        sys.exit("%s: %s" % (SRC, e.code))
    return HEADER + lit + ";\n"


def main():
    check = sys.argv[1:] == ["--check"]
    if sys.argv[1:] and not check:
        sys.exit("usage: gen-agents.py [--check]")
    want = render()
    if check:
        try:
            with open(OUT, encoding="utf-8") as f:
                have = f.read()
        except OSError:
            have = None
        if have != want:
            sys.exit("%s is stale: run python3 scripts/gen-agents.py" % OUT)
        return
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(want)


if __name__ == "__main__":
    main()
