//! The agent catalog as compiled in: integrations/agents.toml, byte for
//! byte (SPEC §10a). [`crate::AgentCatalog::builtin`] parses it.
//!
//! Generated by scripts/gen-agents.py from integrations/agents.toml. Do not
//! edit.

/// The contents of integrations/agents.toml.
pub(crate) static AGENTS_TOML: &str = r#"# Known AI coding agents, for caller evidence (SPEC §10a, §10b "Root
# selection"). Format and rules: docs/AGENTS.md.
#
# A process in a caller's ancestry is an agent when its executable, a name
# it goes by, its script (under an interpreter) or its macOS code signature
# matches an entry here. A match makes handling stricter (an agent
# subject, the agent barrier, proofs refused); a pattern that misses an
# agent lets it ride a terminal grant. A match on the executable's path or
# signature also makes the agent the root of its grants above the caller's
# session, covering every command it runs, so `executables` must name
# agents only, and never an interpreter, which runs whatever it is given
# (the builtin catalog fails to load otherwise). A match on `names`
# (names other programs share, or titles a process gives itself), on
# argv[0], a script or the command name, which a process sets itself, never
# does that. Compiled into the release by scripts/gen-agents.py; users add
# entries under <data>/agents.d/.
#
# Every pattern rests on evidence (M2 plan task M2-10, lesson L-15): a
# real install observed (M2-04's pinned hosts, crates/envcloak-e2e/agents/
# versions.toml, whose layouts and commands the `catalog` tests of
# crates/envcloak-e2e/tests/agent_hosts.rs classify) or the agent's own
# documentation or source, named beside it. `product` names the product
# an entry belongs to, for coverage reporting. `install_trees` names the
# directories the agent's documented installers write to, for the Linux
# standing statement (M2 plan D-10); an agent with none has no Linux
# standing approval. `code_selecting_env` names the runtime variables that
# make the agent's own executable run other code, among those tried on its
# pinned builds (agent_hosts' `code_selecting_env_is_measured` checks each
# entry with an executable identity on both systems), for standing
# approvals (SPEC §10b), which also refuse every dynamic loader variable
# (`LD_*`, `DYLD_*`) for every agent without a list.
#
# Left out for want of evidence: the Cursor IDE (no signature observed).

# Executables that run scripts. For these, the script arguments are matched
# against each agent's `scripts`, and argv[0] against its `names`. A name
# followed by a version (digits and dots, at least one digit: python3.16,
# node22) is the interpreter's too, listed or not (docs/AGENTS.md). Python
# runs kimi-cli (https://github.com/MoonshotAI/kimi-cli, pyproject.toml:
# `kimi` and `kimi-cli` scripts); `Python` is the executable of macOS's
# framework builds.
interpreters = [
  "node",
  "nodejs",
  "bun",
  "deno",
  "python",
  "python3",
  "python3.10",
  "python3.11",
  "python3.12",
  "python3.13",
  "python3.14",
  "python3.15",
  "Python",
]

[[agent]]
id = "claude-code"
name = "Claude Code"
product = "claude-code"
# The native build: ~/.local/share/claude/versions/<version>, or npm's
# @anthropic-ai/claude-code/bin/claude.exe, run through a `claude` link.
executables = ["claude", "claude.exe", "claude/versions/*"]
# The older npm build: node .../@anthropic-ai/claude-code/cli.js, or a
# `claude` script run through its shebang. npm's launcher with install
# scripts off, `node cli-wrapper.cjs`, which starts the native binary.
scripts = [
  "claude",
  "@anthropic-ai/claude-code/cli.js",
  "@anthropic-ai/claude-code/cli-wrapper.cjs",
]
signatures = [{ team = "Q6L2SF6YDW", identifier = "com.anthropic.claude-code" }]
# Set in the environment of the commands it runs (measured: docs/AGENTS.md
# "Host behaviour").
markers = ["CLAUDECODE", "CLAUDE_CODE_ENTRYPOINT", "CLAUDE_CODE_CHILD_SESSION"]
# https://code.claude.com/docs/en/setup: the native installer's versions
# directory, and `npm install -g` into npm's global folder,
# {prefix}/lib/node_modules, the prefix being where node is installed,
# /usr/local by default (https://docs.npmjs.com/cli/v10/configuring-npm/
# folders), /usr for a distribution's node. The package holds the
# platform binary.
install_trees = [
  "~/.local/share/claude/versions",
  "/usr/local/lib/node_modules/@anthropic-ai/claude-code",
  "/usr/lib/node_modules/@anthropic-ai/claude-code",
]
# The native build is a Bun executable: BUN_OPTIONS=--preload=<file> runs
# that file in it first, under its path and its signature (measured on
# 2.1.280; BUN_BE_BUN and NODE_OPTIONS change nothing there).
code_selecting_env = ["BUN_OPTIONS"]

[[agent]]
id = "codex"
name = "Codex"
product = "codex"
# The native binary, also under npm's @openai/codex-<platform>/vendor/.
executables = ["codex"]
# npm's launcher, which starts the native binary.
scripts = ["codex", "@openai/codex/bin/codex.js"]
signatures = [{ team = "2DC432GLL2", identifier = "codex" }]
markers = ["CODEX_THREAD_ID", "CODEX_SANDBOX", "CODEX_SANDBOX_NETWORK_DISABLED"]
# `npm install -g @openai/codex`, in npm's global folder (as above).
install_trees = [
  "/usr/local/lib/node_modules/@openai/codex",
  "/usr/lib/node_modules/@openai/codex",
]

[[agent]]
id = "cursor"
name = "Cursor"
product = "cursor"
# Cursor CLI as its installer lays it out (https://cursor.com/install):
# ~/.local/share/cursor-agent/versions/<version>/, whose cursor-agent
# script runs that directory's own node on its index.js; ~/.local/bin/
# agent and ~/.local/bin/cursor-agent link to the script. The command name
# `agent` is too generic for a pattern. Its process is that node, which
# runs any script (and is signed by the Node.js Foundation, not by
# Cursor), so Cursor is known by its script only, never by an executable:
# it roots no grant above a command's session and has no standing
# approval. The binaries Anysphere signs in the package (cursorsandbox,
# spawn-helper, crepectl, the worker) are not an identity either: the
# sandbox and the spawn helper start whatever command they are given, and
# none was observed in a command's ancestry.
scripts = ["cursor-agent/versions/*/index.js"]
# Set in the commands its agent and its sandbox run (Map C §2).
markers = ["CURSOR_AGENT", "CURSOR_SANDBOX"]

[[agent]]
id = "gemini-cli"
name = "Gemini CLI"
product = "gemini-cli"
# npm's @google/gemini-cli under node: its bundle, or the `gemini` link run
# through its shebang.
scripts = ["gemini", "@google/gemini-cli/bundle/gemini.js"]
# Set in the commands its shell tool runs (https://raw.githubusercontent.
# com/google-gemini/gemini-cli/main/docs/tools/shell.md).
markers = ["GEMINI_CLI"]

[[agent]]
id = "copilot-cli"
name = "GitHub Copilot CLI"
product = "copilot-cli"
# The native binary of npm's platform packages (@github/copilot's
# optionalDependencies), which `node npm-loader.js` starts; on Linux its
# process takes its main thread's name, `MainThread`.
executables = [
  "@github/copilot-linux-x64/copilot",
  "@github/copilot-linux-arm64/copilot",
  "@github/copilot-linuxmusl-x64/copilot",
  "@github/copilot-linuxmusl-arm64/copilot",
  "@github/copilot-darwin-x64/copilot",
  "@github/copilot-darwin-arm64/copilot",
]
# The install script's $PREFIX/bin/copilot (https://raw.githubusercontent.
# com/github/copilot-cli/main/install.sh: $HOME/.local, or /usr/local as
# root) has a path the AWS Copilot CLI also installs to (/usr/local/bin/
# copilot), so `copilot` is a name, not an identity: it makes a process an
# agent and roots nothing above a session.
names = ["copilot"]
# npm's launcher, directly or through the `copilot` link.
scripts = ["copilot", "@github/copilot/npm-loader.js"]
# Observed on the pinned 1.0.90 macOS binary.
signatures = [{ team = "VEKTX9H2N7", identifier = "copilot" }]
# npm's global folder (as above). The binary is a Node single executable
# that refuses NODE_OPTIONS; BUN_OPTIONS and BUN_BE_BUN change nothing
# (measured on 1.0.90).
install_trees = [
  "/usr/local/lib/node_modules/@github/copilot",
  "/usr/lib/node_modules/@github/copilot",
]

[[agent]]
id = "opencode"
name = "OpenCode"
product = "opencode"
# The native binary: npm's opencode-<platform>/bin/opencode, or the install
# script's ~/.opencode/bin/opencode (https://raw.githubusercontent.com/
# anomalyco/opencode/dev/install).
executables = ["opencode"]
# Observed on the pinned 1.18.34 macOS binary.
signatures = [{ team = "5NZ4Q7NXJ4", identifier = "opencode" }]
install_trees = [
  "~/.opencode/bin",
  "/usr/local/lib/node_modules/opencode-ai",
  "/usr/lib/node_modules/opencode-ai",
]
# A Bun executable: BUN_BE_BUN=1 makes it Bun itself, which runs any script
# it is given under OpenCode's path and signature (measured on 1.18.34;
# BUN_OPTIONS and NODE_OPTIONS change nothing there).
code_selecting_env = ["BUN_BE_BUN"]

[[agent]]
id = "kimi"
name = "Kimi"
product = "kimi"
# Kimi Code and kimi-cli both run as `kimi`; their installer tells them
# apart by data root (~/.kimi-code, ~/.kimi). Kimi Code's native binary is
# its install script's ~/.kimi-code/bin/kimi (https://code.kimi.com/
# kimi-code/install.sh); no build of it is pinned, so what runs other
# code in it is not measured and it has no install tree (no Linux standing
# approval).
executables = ["kimi"]
# npm's @moonshot-ai/kimi-code runs under node, which renames its process
# and overwrites its own arguments with `kimi-code` (measured on 2.1.1).
# kimi-cli is Python: its `kimi` and `kimi-cli` scripts (pyproject.toml)
# set the process title `Kimi Code` with setproctitle, which overwrites
# the arguments and, on Linux, the command name; its workers are
# `kimi-code-bg-worker` and `kimi-code-worker` (src/kimi_cli/cli/
# __init__.py, src/kimi_cli/utils/proctitle.py).
names = ["kimi-code", "kimi-cli", "Kimi Code", "kimi-code-bg-worker", "kimi-code-worker"]
scripts = ["kimi", "kimi-cli", "@moonshot-ai/kimi-code/dist/main.mjs"]

[[agent]]
id = "qwen-code"
name = "Qwen Code"
product = "qwen-code"
# npm's @qwen-code/qwen-code under node: its entry script, or the `qwen`
# link run through its shebang.
scripts = ["qwen", "@qwen-code/qwen-code/cli-entry.js"]

[[agent]]
id = "goose"
name = "Goose"
product = "goose"
# The goose CLI, one native binary: its install script puts it at
# $GOOSE_BIN_DIR/goose, ~/.local/bin by default (https://raw.
# githubusercontent.com/aaif-goose/goose/main/download_cli.sh), and the
# desktop app runs the same binary it bundles as `goose serve`
# (ui/desktop/src/main.ts). Its shell tool runs `bash -c <command>` as
# its child, in goose's own session and on its terminal: no session or
# terminal of its own (crates/goose/src/agents/platform_extensions/
# developer/shell.rs, v1.53.0). Measured on 1.53.0's macOS arm64 release:
# the process is `goose` by command name and argv[0], and its signature
# is ad hoc, with no Team ID. `goose` is also a database migration tool's
# command (pressly/goose), so it is a name, not an identity: it makes a
# process an agent and roots nothing above a session, and Goose has no
# install tree (no Linux standing approval).
names = ["goose"]
# Documented as set in the commands it runs (documentation/docs/guides/
# environment-variables.md); 1.53.0's source sets it only for a recipe's
# retry checks (crates/goose/src/agents/retry.rs), so the name above is
# what finds its shell tool's commands. The other variable documented
# there, `AGENT=goose`, is a generic name meant for every agent to set.
markers = ["GOOSE_TERMINAL"]

[[agent]]
id = "aider"
name = "Aider"
product = "aider"
# aider-chat under Python: its console script `aider` (pyproject.toml,
# [project.scripts]), which aider-install, `uv tool install` and pipx put
# in a tool environment whose python runs it (https://aider.chat/docs/
# install.html), or `python -m aider`. When its own standard input is a
# terminal it runs a shell command with pexpect, on a pseudo-terminal of
# its own in a session the command leads; otherwise through `subprocess`
# (aider/run_cmd.py). Known by its script only: it roots no grant above a
# command's session and has no install tree.
scripts = ["aider"]

[[agent]]
id = "fixture"
name = "EnvCloak test fixture agent"
product = "fixture"
# crates/envcloak-testkit/src/bin/fixture-agent.rs, which the acceptance
# tests run as an agent, in CI from the release build. Only a program by
# this name matches, and like every executable here it then roots its
# grants above the caller's session (docs/AGENTS.md "Limits").
executables = ["fixture-agent"]
markers = ["ENVCLOAK_FIXTURE_AGENT"]
"#;
