//! The agent catalog: which processes are AI coding agents (SPEC §10a "An
//! ancestor is Claude Code, Codex, Cursor and so on", §10b "Root
//! selection"). The format and the rules are in docs/AGENTS.md.
//!
//! - [`AgentCatalog::builtin`]: `integrations/agents.toml`, compiled in
//!   (`agents_builtin.rs`, generated by scripts/gen-agents.py).
//! - [`AgentCatalog::load`]: the builtin catalog plus the user's extensions,
//!   `<data>/agents.d/*.toml`. Extensions only add: new agents, and more
//!   patterns, signatures, markers and interpreters for existing ones.
//!   Nothing in them removes or narrows a builtin entry. A file that fails
//!   a check is skipped and reported ([`AgentCatalog::problems`]).
//! - [`AgentCatalog::classify`]: the agent a process is, from its
//!   executable (path, `argv[0]` or command name), a name it goes by, its
//!   script when an interpreter runs it, or its macOS code signature.
//!   Builtin entries are tried first, and the label says which kind matched
//!   ([`CatalogSource`]) and on what ([`MatchBasis`]).
//!
//! A match labels the process an agent, which only tightens: the caller
//! is an agent subject, the agent barrier applies, and its proofs are
//! refused. One use of a match can widen: an agent runs each command in a
//! session of its own, so a grant for it is rooted at the agent process,
//! above the caller's session (`crate::SubjectEvidence`). Only a builtin
//! match on the executable's path or its code signature
//! ([`AgentLabel::may_root_above_session`]) does that (SPEC §10a). A match
//! on what a process says about itself (`argv[0]`, its script, its command
//! name), or one that needed a user extension, roots a grant no higher
//! than the caller's session leader, so it cannot widen a grant to sibling
//! sessions. That includes a match on arguments read only because an
//! extension names an interpreter: the builtin pass uses arguments only
//! where the builtin catalog alone would read them.
//!
//! So a builtin `executables` pattern must name agents only: one that also
//! matched a terminal multiplexer's executable would root grants at it. A
//! name other programs also go by, or one a process gives itself (a
//! process title), goes in `names`, whose matches are always
//! [`MatchBasis::Asserted`]. Neither a builtin `executables` pattern nor a
//! builtin signature may name an interpreter
//! ([`CatalogErrorKind::RuntimeIdentity`]): an interpreter runs whatever
//! script it is given, so its path or signature never names an agent.
//! Errors are value-free: a kind and a line.
//!
//! Each entry also names its `product` ([`AgentLabel::product`], for
//! coverage reporting) and, in the builtin catalog only, the
//! `install_trees` its documented installers write to
//! ([`AgentCatalog::within_install_tree`], for the Linux standing
//! statement, M2 plan D-10) and the `code_selecting_env` variables that
//! make its own executable run other code, as measured on its builds
//! ([`AgentCatalog::code_selecting_env`], for standing approvals, SPEC
//! §10b). None of them changes what matches.

use std::ffi::{OsStr, OsString};
use std::fs::{File, OpenOptions};
use std::io::{self, Read};
use std::os::unix::ffi::OsStrExt;
use std::os::unix::fs::{MetadataExt, OpenOptionsExt};
use std::path::Path;

use envcloak_sys::{Argv, ProcInfo};
use toml_edit::{Document, Item, TableLike, Value};

use crate::agents_builtin::AGENTS_TOML;
use crate::manifest::valid_project_name;
use crate::names::EnvName;

/// The directory under the data directory that holds extensions.
pub const AGENTS_DIR: &str = "agents.d";
/// The largest catalog file accepted, in bytes.
pub const MAX_CATALOG_FILE: usize = 64 * 1024;
/// Extension files read; the rest (in name order) are reported and
/// skipped.
pub const MAX_EXTENSION_FILES: usize = 16;
/// Agents one file may define.
const MAX_AGENTS_PER_FILE: usize = 64;
/// Agents in the merged catalog.
const MAX_AGENTS: usize = 256;
/// Entries in any one list (`executables`, `scripts`, `signatures`,
/// `markers`, `interpreters`) of one file.
const MAX_LIST: usize = 32;
/// Components in a pattern.
const MAX_COMPONENTS: usize = 8;
/// Bytes in a pattern.
const MAX_PATTERN: usize = 256;
/// Bytes in an agent's display name.
const MAX_NAME: usize = 64;
/// Components in an install tree.
const MAX_TREE_COMPONENTS: usize = 16;
/// Bytes in a name (`names`).
const MAX_NAME_BYTES: usize = 64;
/// The longest command name a kernel keeps: 15 bytes on Linux
/// (`TASK_COMM_LEN` less its NUL), 16 on macOS (`MAXCOMLEN`). A name at
/// least this long may have been cut to it.
const COMM_CUT: usize = 15;
/// What Linux adds to the path of an executable that was removed (or
/// renamed over) while it runs (`/proc/<pid>/exe`, proc(5)).
const DELETED: &[u8] = b" (deleted)";
/// How many arguments of an interpreter are looked at for its script:
/// the first few that are not options, among the first few in all, which
/// are all the kernel's view keeps after `argv[0]`
/// ([`envcloak_sys::MAX_ARGV`]).
const SCRIPT_ARGS: usize = 3;
const SCRIPT_ARGS_SCANNED: usize = envcloak_sys::MAX_ARGV - 1;

/// The prefixes of the dynamic loaders' environment variables: Linux
/// `ld.so`'s (`LD_PRELOAD`, `LD_AUDIT`, `LD_LIBRARY_PATH`, ...) and macOS
/// `dyld`'s (`DYLD_INSERT_LIBRARIES`, `DYLD_LIBRARY_PATH`, ...). Each can
/// make a dynamically linked executable load code it names
/// ([`AgentCatalog::env_selects_code`]).
pub const LOADER_ENV_PREFIXES: [&str; 2] = ["LD_", "DYLD_"];

/// Where a catalog entry came from.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum CatalogSource {
    /// `integrations/agents.toml`, shipped in the release.
    Builtin,
    /// A file in `<data>/agents.d/`.
    Extension,
}

/// What a match rests on (SPEC §10a: an executable's identity is
/// evidence; argv is caller-asserted).
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum MatchBasis {
    /// The executable's path as the kernel reports it, or the macOS code
    /// signature the kernel validated when it started.
    Executable,
    /// What the process says about itself, which it can set: its
    /// `argv[0]`, an interpreter's script argument, or its command name
    /// (Linux: `prctl(PR_SET_NAME)`, or the name of a link it was run
    /// through). Also an environment marker's label.
    Asserted,
}

/// What an agent is shown as. Display only (SPEC §10b `kind:
/// agent(label)`), except that [`AgentLabel::may_root_above_session`]
/// limits where a grant may be rooted.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct AgentLabel {
    /// The catalog id: `claude-code`, `codex`, ...
    pub id: String,
    /// The display name: `Claude Code`, ...
    pub name: String,
    /// The product the entry belongs to, for coverage reporting (`agents
    /// status`, the installers): `claude-code`, `cursor`, `kimi`, ... One
    /// product can be several programs (Kimi Code and kimi-cli both run
    /// as `kimi`, and their installer tells them apart by data root), and
    /// it carries no version: the evidence never names one.
    pub product: String,
    /// Whether a builtin entry matched, or only an extension did.
    pub source: CatalogSource,
    /// Whether the match rests on the executable, or only on what the
    /// process says about itself.
    pub basis: MatchBasis,
}

impl AgentLabel {
    /// Whether this match may root a grant above the caller's session: a
    /// builtin entry matched the executable's path or its code signature.
    /// Any other match roots a grant no higher than the session rules
    /// would (SPEC §10b "Root selection").
    pub fn may_root_above_session(&self) -> bool {
        self.source == CatalogSource::Builtin && self.basis == MatchBasis::Executable
    }
}

/// What is wrong with a catalog file. Every message is fixed text.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum CatalogErrorKind {
    TooLarge,
    NotUtf8,
    /// Not TOML.
    Syntax,
    DuplicateKey,
    UnknownKey,
    WrongType,
    /// An agent without `id`, or a new agent without `name`.
    MissingKey,
    InvalidId,
    InvalidName,
    InvalidPattern,
    InvalidInterpreter,
    InvalidSignature,
    InvalidMarker,
    /// One file defines an id twice.
    DuplicateId,
    /// An agent that matches nothing: no executables, names, scripts,
    /// signatures or markers.
    EmptyAgent,
    /// More entries than a list, a file or the catalog may hold.
    TooMany,
    /// `agents.d` is a symlink, not a directory, another user's, or
    /// writable by group or others.
    UnsafeDirectory,
    /// The file is a symlink.
    Symlink,
    NotRegularFile,
    /// Owned by another user.
    NotOwned,
    /// Writable by group or others.
    Writable,
    /// An install tree that is not an absolute or `~/` path of names and
    /// `*`.
    InvalidInstallTree,
    /// `install_trees` or `code_selecting_env` in an extension: only the
    /// builtin catalog says where an agent's own installers put it (M2
    /// plan D-10) and what its builds were measured to do.
    BuiltinOnly,
    /// Builtin catalog only: an `executables` pattern whose last component,
    /// or a signature whose identifier, is one of `interpreters`. An
    /// interpreter runs whatever script it is given, so its path or its
    /// signature is never an agent's identity.
    RuntimeIdentity,
    /// A name (`names`) that is empty, longer than 64 bytes, holds `/`, or
    /// holds a control or invisible character.
    InvalidAgentName,
    /// Another I/O error.
    Io(io::ErrorKind),
}

impl CatalogErrorKind {
    fn message(self) -> &'static str {
        use CatalogErrorKind as K;
        match self {
            K::TooLarge => "the catalog file is larger than 64 KiB",
            K::NotUtf8 => "the catalog file is not UTF-8",
            K::Syntax => "not valid TOML",
            K::DuplicateKey => "a key is defined twice",
            K::UnknownKey => "unknown key",
            K::WrongType => "a value has the wrong type",
            K::MissingKey => "an agent needs an id, and a new agent a name",
            K::InvalidId => {
                "invalid agent id or product: lowercase ASCII letters, digits and inner -, at \
                 most 32 bytes"
            }
            K::InvalidName => {
                "invalid agent name: 1 to 64 bytes, without control or invisible characters"
            }
            K::InvalidPattern => {
                "invalid pattern: path components separated by /, each a name or *, with at least \
                 one name, at most 8 components and 256 bytes"
            }
            K::InvalidInterpreter => "invalid interpreter: one file name, without / or *",
            K::InvalidSignature => {
                "invalid signature: { identifier = \"<signing id>\", team = \"<10-character Team \
                 ID>\" }, team optional"
            }
            K::InvalidMarker => {
                "invalid marker or code_selecting_env: an environment variable name (an ASCII \
                 letter or _, then letters, digits or _)"
            }
            K::DuplicateId => "an agent id is defined twice in one file",
            K::EmptyAgent => {
                "an agent must list executables, names, scripts, signatures or markers"
            }
            K::TooMany => "too many entries",
            K::UnsafeDirectory => {
                "agents.d must be a directory of this user, not a symlink, and not writable by \
                 group or others"
            }
            K::Symlink => "the catalog file is a symlink, which is refused",
            K::NotRegularFile => "the catalog file is not a regular file",
            K::NotOwned => "the catalog file is owned by another user",
            K::Writable => "the catalog file is writable by group or others",
            K::InvalidInstallTree => {
                "invalid install tree: /<path> or ~/<path>, components separated by /, each a \
                 name or *, at most 16 components and 256 bytes"
            }
            K::BuiltinOnly => {
                "install_trees and code_selecting_env may be set only in the builtin catalog"
            }
            K::RuntimeIdentity => {
                "an executable pattern or a signature names an interpreter, which runs any script"
            }
            K::InvalidAgentName => {
                "invalid name: 1 to 64 bytes, without /, control or invisible characters"
            }
            K::Io(_) => "cannot read the catalog file",
        }
    }
}

/// A catalog error: a kind and, for content errors, the line.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct CatalogError {
    kind: CatalogErrorKind,
    line: Option<u32>,
}

impl CatalogError {
    pub fn kind(&self) -> CatalogErrorKind {
        self.kind
    }

    pub fn line(&self) -> Option<u32> {
        self.line
    }
}

impl From<CatalogErrorKind> for CatalogError {
    fn from(kind: CatalogErrorKind) -> Self {
        CatalogError { kind, line: None }
    }
}

impl core::fmt::Display for CatalogError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        if let Some(line) = self.line {
            write!(f, "line {line}: ")?;
        }
        f.write_str(self.kind.message())?;
        if let CatalogErrorKind::Io(k) = self.kind {
            write!(f, " ({k})")?;
        }
        Ok(())
    }
}

impl std::error::Error for CatalogError {}

/// An extension file that was skipped, or an `agents.d` that was not read
/// (`file` is then `agents.d`).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CatalogProblem {
    /// The file's name in `agents.d`.
    pub file: OsString,
    pub error: CatalogError,
}

/// What [`AgentCatalog::extension_files`] read.
#[derive(Debug)]
pub struct ExtensionFiles {
    /// Why the directory itself was not read (none when it is absent).
    pub directory: Option<CatalogError>,
    /// Each extension file by name, in name order: its bytes, or why it is
    /// skipped.
    pub files: Vec<(OsString, Result<Vec<u8>, CatalogError>)>,
}

/// One path component of a pattern.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
enum Component {
    Name(Vec<u8>),
    /// `*`: any one component.
    Any,
}

/// A path suffix: `claude`, `claude/versions/*`,
/// `@anthropic-ai/claude-code/cli.js`. It matches a path whose last
/// components are these, `*` standing for any one.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
struct Pattern(Vec<Component>);

impl Pattern {
    fn parse(s: &str) -> Option<Pattern> {
        if s.is_empty() || s.len() > MAX_PATTERN {
            return None;
        }
        let mut out = Vec::new();
        for c in s.split('/') {
            if c.is_empty() || c == "." || c == ".." || c.chars().any(char::is_control) {
                return None;
            }
            if c == "*" {
                out.push(Component::Any);
            } else if c.contains('*') {
                return None;
            } else {
                out.push(Component::Name(c.as_bytes().to_vec()));
            }
        }
        let named = out.iter().any(|c| matches!(c, Component::Name(_)));
        (named && out.len() <= MAX_COMPONENTS).then_some(Pattern(out))
    }

    /// Whether `path`'s last components are this pattern's. Empty and `.`
    /// components of `path` are skipped, so `./claude` and `claude/` are
    /// `claude`.
    fn matches(&self, path: &[u8]) -> bool {
        let comps: Vec<&[u8]> = path
            .split(|b| *b == b'/')
            .filter(|c| !c.is_empty() && *c != b".")
            .collect();
        if comps.len() < self.0.len() {
            return false;
        }
        let tail = &comps[comps.len() - self.0.len()..];
        self.0.iter().zip(tail).all(|(p, c)| match p {
            Component::Any => true,
            Component::Name(n) => n.as_slice() == *c,
        })
    }
}

/// Where an agent's own installers put it: a directory, as an absolute
/// path (`/usr/local/lib/node_modules/@openai/codex`) or one under the
/// home directory (`~/.local/share/claude/versions`), each component a
/// name or `*` (any one component). An executable is in the tree when its
/// path lies strictly below it (M2 plan D-10: the Linux standing
/// statement refuses an identity outside every tree of its agent).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
struct InstallTree {
    /// Whether the path starts at the home directory.
    home: bool,
    components: Vec<Component>,
}

impl InstallTree {
    fn parse(s: &str) -> Option<InstallTree> {
        if s.len() > MAX_PATTERN {
            return None;
        }
        let (home, rest) = match (s.strip_prefix("~/"), s.strip_prefix('/')) {
            (Some(rest), _) => (true, rest),
            (None, Some(rest)) => (false, rest),
            (None, None) => return None,
        };
        let mut components = Vec::new();
        for c in rest.split('/') {
            if c.is_empty() || c == "." || c == ".." || c.chars().any(char::is_control) {
                return None;
            }
            if c == "*" {
                components.push(Component::Any);
            } else if c.contains('*') {
                return None;
            } else {
                components.push(Component::Name(c.as_bytes().to_vec()));
            }
        }
        (components.len() <= MAX_TREE_COMPONENTS).then_some(InstallTree { home, components })
    }

    /// Whether `path` lies strictly below this tree. `path` must be
    /// absolute and hold no `.` or `..` component (the kernel's paths do
    /// not); `home` must be absolute too, or a `~/` tree matches nothing.
    fn contains(&self, path: &Path, home: Option<&Path>) -> bool {
        let comps = |p: &Path| -> Option<Vec<Vec<u8>>> {
            let b = p.as_os_str().as_bytes();
            if !b.starts_with(b"/") {
                return None;
            }
            let parts: Vec<&[u8]> = b.split(|c| *c == b'/').filter(|c| !c.is_empty()).collect();
            if parts.iter().any(|c| *c == b"." || *c == b"..") {
                return None;
            }
            Some(parts.into_iter().map(<[u8]>::to_vec).collect())
        };
        let Some(path) = comps(path) else {
            return false;
        };
        let mut want: Vec<Component> = Vec::new();
        if self.home {
            let Some(home) = home.and_then(comps) else {
                return false;
            };
            want.extend(home.into_iter().map(Component::Name));
        }
        want.extend(self.components.iter().cloned());
        path.len() > want.len()
            && want.iter().zip(&path).all(|(w, c)| match w {
                Component::Any => true,
                Component::Name(n) => n == c,
            })
    }
}

/// A macOS code signature an agent is signed with.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
struct Signature {
    identifier: String,
    /// `None`: any team, or none.
    team: Option<String>,
}

/// One agent: its id, its name, and what identifies it, each entry tagged
/// with where it came from.
#[derive(Debug, Clone)]
struct Agent {
    id: String,
    name: String,
    product: String,
    executables: Vec<(Pattern, CatalogSource)>,
    /// Names its process goes by that are not an identity: matched against
    /// its executable's file name, `argv[0]` and its command name, and
    /// always [`MatchBasis::Asserted`].
    names: Vec<(Vec<u8>, CatalogSource)>,
    scripts: Vec<(Pattern, CatalogSource)>,
    signatures: Vec<(Signature, CatalogSource)>,
    markers: Vec<(String, CatalogSource)>,
    /// From the builtin catalog only ([`CatalogErrorKind::BuiltinOnly`]).
    install_trees: Vec<InstallTree>,
    /// From the builtin catalog only ([`CatalogErrorKind::BuiltinOnly`]).
    code_selecting_env: Vec<String>,
}

/// The known agents. See the module documentation.
#[derive(Debug, Clone)]
pub struct AgentCatalog {
    agents: Vec<Agent>,
    interpreters: Vec<(Vec<u8>, CatalogSource)>,
    problems: Vec<CatalogProblem>,
}

impl AgentCatalog {
    /// The catalog compiled into this build.
    ///
    /// # Panics
    /// Never in a tested build: the `agents` test parses it.
    pub fn builtin() -> Self {
        let mut cat = AgentCatalog {
            agents: Vec::new(),
            interpreters: Vec::new(),
            problems: Vec::new(),
        };
        let file = parse_builtin(AGENTS_TOML.as_bytes()).expect("the builtin agent catalog parses");
        cat.merge(file, CatalogSource::Builtin);
        cat
    }

    /// The text [`AgentCatalog::builtin`] parses: integrations/agents.toml
    /// as compiled in.
    pub fn builtin_source() -> &'static str {
        AGENTS_TOML
    }

    /// The builtin catalog plus the extensions in `<data_dir>/agents.d/`.
    /// A missing directory is no extensions; an unsafe one, or a file that
    /// fails a check, is reported in [`AgentCatalog::problems`] and
    /// skipped.
    pub fn load(data_dir: &Path) -> Self {
        let mut cat = Self::builtin();
        let read = Self::extension_files(data_dir);
        if let Some(e) = read.directory {
            cat.problem(OsStr::new(AGENTS_DIR), e);
            return cat;
        }
        for (name, bytes) in read.files {
            match bytes.and_then(|b| parse_catalog(&b)) {
                Ok(file) if cat.agents.len() + file.new_ids(&cat) > MAX_AGENTS => {
                    cat.problem(&name, CatalogErrorKind::TooMany.into());
                }
                Ok(file) if file.agents.iter().any(FileAgent::has_builtin_only) => {
                    let line = file
                        .agents
                        .iter()
                        .find(|a| a.has_builtin_only())
                        .and_then(|a| a.line);
                    cat.problem(
                        &name,
                        CatalogError {
                            kind: CatalogErrorKind::BuiltinOnly,
                            line,
                        },
                    );
                }
                Ok(file) if file.unnamed_new(&cat).is_some() => {
                    let line = file.unnamed_new(&cat);
                    cat.problem(
                        &name,
                        CatalogError {
                            kind: CatalogErrorKind::MissingKey,
                            line: line.flatten(),
                        },
                    );
                }
                Ok(file) => cat.merge(file, CatalogSource::Extension),
                Err(e) => cat.problem(&name, e),
            }
        }
        cat
    }

    /// The extension files [`AgentCatalog::load`] reads from
    /// `<data_dir>/agents.d/`, with every check it applies before parsing:
    /// the directory opened without following a link, a directory of this
    /// user's that no one else may write; each `*.toml` (not hidden) opened
    /// beneath it without following a link, a regular file of this user's
    /// that no one else may write, at most [`MAX_CATALOG_FILE`] bytes; at
    /// most [`MAX_EXTENSION_FILES`] of them, by name. In name order, each
    /// with its bytes or why it is skipped. For a probe daemon of
    /// `envcloak agents status --probe` (M2 plan M2-28), which must know the
    /// person's agents as their daemon does (the verifier's review: a probe
    /// daemon with the builtin catalog alone judged an agent only an
    /// extension names to be a terminal, and approved for it).
    pub fn extension_files(data_dir: &Path) -> ExtensionFiles {
        let none = |directory| ExtensionFiles {
            directory,
            files: Vec::new(),
        };
        let dir_path = data_dir.join(AGENTS_DIR);
        let dir = match OpenOptions::new()
            .read(true)
            .custom_flags(libc::O_DIRECTORY | libc::O_NOFOLLOW | libc::O_CLOEXEC)
            .open(&dir_path)
        {
            Ok(d) => d,
            Err(e) if e.kind() == io::ErrorKind::NotFound => return none(None),
            Err(e) => {
                let kind = match e.raw_os_error() {
                    Some(libc::ELOOP | libc::ENOTDIR) => CatalogErrorKind::UnsafeDirectory,
                    _ => CatalogErrorKind::Io(e.kind()),
                };
                return none(Some(kind.into()));
            }
        };
        let trusted = dir.metadata().is_ok_and(|m| {
            m.is_dir() && m.uid() == envcloak_sys::effective_uid() && m.mode() & 0o022 == 0
        });
        if !trusted {
            return none(Some(CatalogErrorKind::UnsafeDirectory.into()));
        }
        // The listing goes by path; each file is then opened through the
        // checked directory's handle, so only files in it are read.
        let mut names: Vec<OsString> = match std::fs::read_dir(&dir_path) {
            Ok(entries) => entries
                .filter_map(Result::ok)
                .map(|e| e.file_name())
                .filter(|n| {
                    let b = n.as_bytes();
                    b.ends_with(b".toml") && !b.starts_with(b".")
                })
                .collect(),
            Err(e) => return none(Some(CatalogErrorKind::Io(e.kind()).into())),
        };
        names.sort();
        let files = names
            .into_iter()
            .enumerate()
            .map(|(i, name)| {
                let bytes = if i >= MAX_EXTENSION_FILES {
                    Err(CatalogErrorKind::TooMany.into())
                } else {
                    read_extension(&dir, &name)
                };
                (name, bytes)
            })
            .collect();
        ExtensionFiles {
            directory: None,
            files,
        }
    }

    fn problem(&mut self, file: &OsStr, error: CatalogError) {
        self.problems.push(CatalogProblem {
            file: file.to_owned(),
            error,
        });
    }

    /// The extension files skipped, and why.
    pub fn problems(&self) -> &[CatalogProblem] {
        &self.problems
    }

    /// The ids of the known agents, builtin first.
    pub fn ids(&self) -> impl Iterator<Item = &str> {
        self.agents.iter().map(|a| a.id.as_str())
    }

    /// The product of agent `id` ([`AgentLabel::product`]), if the catalog
    /// knows it.
    pub fn product(&self, id: &str) -> Option<&str> {
        self.agents
            .iter()
            .find(|a| a.id == id)
            .map(|a| a.product.as_str())
    }

    /// Whether `exe`, an absolute executable path as the kernel reports
    /// it, lies within one of the install trees the builtin catalog lists
    /// for agent `id`; `~/` trees start at `home`. `false` for an agent
    /// with none, an unknown id, and a path with `.` or `..` components.
    /// For the Linux standing statement (M2 plan D-10, task M2-15:
    /// `identity_outside_install_tree`): a renamed copy of any program
    /// matches an agent by path, never by where its installer put it.
    /// `false` too for an executable whose file name is an interpreter's
    /// ([`interpreter_name`], the builtin catalog's interpreters): an
    /// interpreter in an agent's tree is still no identity.
    pub fn within_install_tree(&self, id: &str, exe: &Path, home: Option<&Path>) -> bool {
        let name = last_component(exe.as_os_str().as_bytes());
        let name = name.strip_suffix(DELETED).unwrap_or(name);
        !self.interpreter_named(name, false)
            && self
                .agents
                .iter()
                .find(|a| a.id == id)
                .is_some_and(|a| a.install_trees.iter().any(|t| t.contains(exe, home)))
    }

    /// The environment variables that make agent `id`'s own executable run
    /// code other than the agent's (a preload, a script in place of its
    /// own), as the builtin catalog records them, measured on its pinned
    /// builds (`agents-e2e` checks each): empty for an agent with none
    /// measured, and for an unknown id. For standing approvals (SPEC §10b):
    /// an agent process whose environment sets one runs code a program
    /// chose under the agent's path and signature.
    pub fn code_selecting_env(&self, id: &str) -> &[String] {
        self.agents
            .iter()
            .find(|a| a.id == id)
            .map_or(&[], |a| a.code_selecting_env.as_slice())
    }

    /// Whether a variable named `name`, set in the environment of agent
    /// `id`'s process, may make that process's executable run code other
    /// than the agent's: any dynamic loader variable
    /// ([`LOADER_ENV_PREFIXES`]), for every agent and an unknown id alike,
    /// or one of its entry's [`AgentCatalog::code_selecting_env`]. The rule
    /// standing approvals apply (SPEC §10b, task M2-15).
    ///
    /// The loader variables need no measurement: every dynamically linked
    /// executable the kernel does not protect loads what they name, as
    /// SPEC §6.6 refuses them for a registered launch. Measured on the
    /// pinned builds all the same (docs/AGENTS.md): `DYLD_INSERT_LIBRARIES`
    /// runs a library in OpenCode's macOS build, whose signature allows
    /// it, and not in Claude Code's, Codex's or Copilot CLI's. A
    /// `code_selecting_env` list holds only what was tried and seen to run
    /// code, so it never stands for every such variable alone.
    pub fn env_selects_code(&self, id: &str, name: &[u8]) -> bool {
        LOADER_ENV_PREFIXES
            .iter()
            .any(|p| name.starts_with(p.as_bytes()))
            || self
                .code_selecting_env(id)
                .iter()
                .any(|v| v.as_bytes() == name)
    }

    /// Every environment marker the catalog knows, for the CLI's claims
    /// ([`crate::Claims::from_env`]).
    pub fn markers(&self) -> impl Iterator<Item = &str> {
        self.agents
            .iter()
            .flat_map(|a| a.markers.iter().map(|(m, _)| m.as_str()))
    }

    /// The agent that sets marker `name`, if the catalog knows one. A
    /// marker is a claim: the label's basis is [`MatchBasis::Asserted`].
    pub fn agent_for_marker(&self, name: &str) -> Option<AgentLabel> {
        self.agents.iter().find_map(|a| {
            a.markers
                .iter()
                .find(|(m, _)| m == name)
                .map(|(_, source)| label(a, *source, MatchBasis::Asserted))
        })
    }

    /// Whether `p` looks like an interpreter by its executable or command
    /// name, or by `argv[0]` when `argv` is given. Extension interpreters
    /// count only when `extensions` is set.
    fn interpreter(&self, p: &ProcInfo, extensions: bool, argv: Option<&Argv>) -> bool {
        let names = [
            exe_path(p).map(last_component),
            Some(p.comm.as_bytes()),
            argv.and_then(Argv::first)
                .map(|a| last_component(a.as_bytes())),
        ];
        names
            .iter()
            .flatten()
            .any(|n| self.interpreter_named(n, extensions))
    }

    /// Whether `name` is an interpreter's ([`interpreter_name`]): one the
    /// builtin catalog lists, or with `extensions` set one an extension
    /// lists.
    fn interpreter_named(&self, name: &[u8], extensions: bool) -> bool {
        self.interpreters
            .iter()
            .filter(|(_, s)| extensions || *s == CatalogSource::Builtin)
            .any(|(i, _)| interpreter_name(name, i))
    }

    /// Whether the catalog reads `p`'s arguments: its executable is hidden
    /// (so `argv[0]` stands in for it), or its executable or command name
    /// is an interpreter (so its script decides). Extension interpreters
    /// count only when `extensions` is set.
    fn reads_argv(&self, p: &ProcInfo, extensions: bool) -> bool {
        p.exe.is_none() || self.interpreter(p, extensions, None)
    }

    /// Whether classifying `p` needs its arguments: its executable is
    /// hidden (so `argv[0]` stands in for it), or it runs an interpreter,
    /// builtin or from an extension (so its script decides).
    pub fn needs_argv(&self, p: &ProcInfo) -> bool {
        self.reads_argv(p, true)
    }

    /// The agent `p` is, if any. Builtin entries are tried first; the
    /// label's [`AgentLabel::source`] says whether one matched. Within
    /// each pass, a match on the executable's path or its signature is
    /// preferred to one on what the process says about itself; the label's
    /// [`AgentLabel::basis`] says which it was.
    ///
    /// `argv[0]`, the script and the command name are the process's own
    /// word (SPEC §10a "Environment markers and argv": caller-asserted), so
    /// a match on them is [`MatchBasis::Asserted`], which roots no grant
    /// above the caller's session (review finding F-37). So is a match on
    /// an entry's `names`, its executable's file name included: a name
    /// other programs share is never an identity.
    ///
    /// The executable's path is taken without the ` (deleted)` Linux adds
    /// once the file a process runs was removed or renamed over (an agent
    /// or a node that updated itself while it ran): the process still runs
    /// the file that path named. A path whose file name is an
    /// interpreter's ([`interpreter_name`]) matches no `executables`
    /// pattern, a `*` included: an interpreter runs whatever script it is
    /// given, so it is read by its script, as an interpreter anywhere is.
    ///
    /// Each pass uses `p`'s arguments only where that pass's catalog would
    /// read them itself ([`AgentCatalog::needs_argv`] reads them for either
    /// pass). Arguments read only because an extension names an
    /// interpreter are not builtin evidence: a match on them (its `argv[0]`
    /// or its script, even against a builtin pattern) is an extension
    /// match (review finding F-36).
    pub fn classify(&self, p: &ProcInfo) -> Option<AgentLabel> {
        let path = exe_path(p);
        let exe_name = path.map(last_component);
        let comm = p.comm.as_bytes();
        let signature = p.exe.as_ref().and_then(|e| e.signature.as_ref());
        for source in [CatalogSource::Builtin, CatalogSource::Extension] {
            let extensions = source == CatalogSource::Extension;
            let argv = if self.reads_argv(p, extensions) {
                p.argv.as_ref()
            } else {
                None
            };
            let interpreter = self.interpreter(p, extensions, argv);
            let scripts = if interpreter {
                script_args(argv)
            } else {
                Vec::new()
            };
            let said: Vec<&[u8]> = [Some(comm), argv.and_then(Argv::first).map(OsStr::as_bytes)]
                .into_iter()
                .flatten()
                .filter(|n| !n.is_empty())
                .collect();
            let argv0_name = argv
                .and_then(Argv::first)
                .map(|a| last_component(a.as_bytes()))
                .filter(|n| !n.is_empty());
            let counts = |s: &CatalogSource| extensions || *s == CatalogSource::Builtin;
            // An executable whose file name is an interpreter's runs
            // whatever script it is given: its path names no agent, even
            // where a pattern's `*` takes it in (`claude/versions/*` and a
            // node placed there). Its script decides, as for any
            // interpreter, and roots nothing above the session.
            let path_names_agent =
                path.filter(|_| !exe_name.is_some_and(|n| self.interpreter_named(n, extensions)));
            let by_executable = |a: &Agent| {
                let by_path = path_names_agent.is_some_and(|path| {
                    a.executables
                        .iter()
                        .filter(|(_, s)| counts(s))
                        .any(|(pat, _)| pat.matches(path))
                });
                by_path
                    || signature.is_some_and(|sig| {
                        a.signatures
                            .iter()
                            .filter(|(_, s)| counts(s))
                            .any(|(want, _)| {
                                want.identifier == sig.identifier
                                    && want
                                        .team
                                        .as_ref()
                                        .is_none_or(|t| sig.team_id.as_ref() == Some(t))
                            })
                    })
            };
            let by_assertion = |a: &Agent| {
                a.executables
                    .iter()
                    .filter(|(_, s)| counts(s))
                    .any(|(pat, _)| said.iter().any(|n| pat.matches(n)))
                    || a.names.iter().filter(|(_, s)| counts(s)).any(|(n, _)| {
                        exe_name == Some(n.as_slice())
                            || argv0_name == Some(n.as_slice())
                            || comm_names(comm, n)
                    })
                    || a.scripts
                        .iter()
                        .filter(|(_, s)| counts(s))
                        .any(|(pat, _)| scripts.iter().any(|n| pat.matches(n)))
            };
            if let Some(a) = self.agents.iter().find(|a| by_executable(a)) {
                return Some(label(a, source, MatchBasis::Executable));
            }
            if let Some(a) = self.agents.iter().find(|a| by_assertion(a)) {
                return Some(label(a, source, MatchBasis::Asserted));
            }
        }
        None
    }

    fn merge(&mut self, file: CatalogFile, source: CatalogSource) {
        for i in file.interpreters {
            if !self.interpreters.iter().any(|(have, _)| *have == i) {
                self.interpreters.push((i, source));
            }
        }
        for new in file.agents {
            let tag = |v: Vec<Pattern>| v.into_iter().map(|p| (p, source)).collect::<Vec<_>>();
            match self.agents.iter_mut().find(|a| a.id == new.id) {
                // An existing agent keeps its name and product.
                Some(a) => {
                    a.executables.extend(tag(new.executables));
                    a.names.extend(new.names.into_iter().map(|n| (n, source)));
                    a.scripts.extend(tag(new.scripts));
                    a.signatures
                        .extend(new.signatures.into_iter().map(|s| (s, source)));
                    a.markers
                        .extend(new.markers.into_iter().map(|m| (m, source)));
                    a.install_trees.extend(new.install_trees);
                    a.code_selecting_env.extend(new.code_selecting_env);
                }
                None => self.agents.push(Agent {
                    // A new agent always has a name: `load` refuses an
                    // extension without one, and the builtin file names each.
                    name: new.name.unwrap_or_else(|| new.id.clone()),
                    product: new.product.unwrap_or_else(|| new.id.clone()),
                    install_trees: new.install_trees,
                    code_selecting_env: new.code_selecting_env,
                    id: new.id,
                    executables: tag(new.executables),
                    names: new.names.into_iter().map(|n| (n, source)).collect(),
                    scripts: tag(new.scripts),
                    signatures: new.signatures.into_iter().map(|s| (s, source)).collect(),
                    markers: new.markers.into_iter().map(|m| (m, source)).collect(),
                }),
            }
        }
    }
}

fn label(a: &Agent, source: CatalogSource, basis: MatchBasis) -> AgentLabel {
    AgentLabel {
        id: a.id.clone(),
        name: a.name.clone(),
        product: a.product.clone(),
        source,
        basis,
    }
}

fn last_component(path: &[u8]) -> &[u8] {
    path.rsplit(|b| *b == b'/')
        .find(|c| !c.is_empty())
        .unwrap_or(path)
}

/// The path of the executable `p` runs, as the kernel reports it, without
/// the ` (deleted)` Linux adds once that file was removed or renamed over
/// while it runs: the process still runs the file the path named (see
/// [`AgentCatalog::classify`]). `None` when it is hidden or empty.
fn exe_path(p: &ProcInfo) -> Option<&[u8]> {
    let path = p.exe.as_ref()?.path.as_os_str().as_bytes();
    let path = path.strip_suffix(DELETED).unwrap_or(path);
    (!path.is_empty()).then_some(path)
}

/// Whether the command name `comm` is `name`, or `name` cut to the length
/// a kernel keeps ([`COMM_CUT`] bytes or more).
fn comm_names(comm: &[u8], name: &[u8]) -> bool {
    !comm.is_empty()
        && (comm == name
            || (comm.len() >= COMM_CUT && name.len() > comm.len() && name.starts_with(comm)))
}

/// The arguments of an interpreter that may name its script: the first
/// [`SCRIPT_ARGS`] that are not options, among the first
/// [`SCRIPT_ARGS_SCANNED`] after `argv[0]`. Borrowed from the wiped
/// [`Argv`], never copied.
fn script_args(argv: Option<&Argv>) -> Vec<&[u8]> {
    let Some(argv) = argv else {
        return Vec::new();
    };
    argv.iter()
        .skip(1)
        .take(SCRIPT_ARGS_SCANNED)
        .map(OsStr::as_bytes)
        .filter(|a| !a.is_empty() && !a.starts_with(b"-"))
        .take(SCRIPT_ARGS)
        .collect()
}

/// Opens `name` in the checked `agents.d` handle and reads it, after
/// `fstat` shows a regular file of this user that group and others cannot
/// write, no larger than [`MAX_CATALOG_FILE`].
fn read_extension(dir: &File, name: &OsStr) -> Result<Vec<u8>, CatalogError> {
    let file = envcloak_sys::open_beneath(dir, name).map_err(|e| {
        if e.raw_os_error() == Some(libc::ELOOP) {
            CatalogErrorKind::Symlink
        } else {
            CatalogErrorKind::Io(e.kind())
        }
    })?;
    let m = file
        .metadata()
        .map_err(|e| CatalogErrorKind::Io(e.kind()))?;
    if !m.file_type().is_file() {
        return Err(CatalogErrorKind::NotRegularFile.into());
    }
    if m.uid() != envcloak_sys::effective_uid() {
        return Err(CatalogErrorKind::NotOwned.into());
    }
    if m.mode() & 0o022 != 0 {
        return Err(CatalogErrorKind::Writable.into());
    }
    let mut bytes = Vec::new();
    file.take(MAX_CATALOG_FILE as u64 + 1)
        .read_to_end(&mut bytes)
        .map_err(|e| CatalogErrorKind::Io(e.kind()))?;
    if bytes.len() > MAX_CATALOG_FILE {
        return Err(CatalogErrorKind::TooLarge.into());
    }
    Ok(bytes)
}

/// One parsed catalog file.
#[derive(Debug)]
struct CatalogFile {
    interpreters: Vec<Vec<u8>>,
    agents: Vec<FileAgent>,
}

impl CatalogFile {
    /// How many of this file's agents `cat` does not have yet.
    fn new_ids(&self, cat: &AgentCatalog) -> usize {
        self.agents
            .iter()
            .filter(|a| !cat.agents.iter().any(|have| have.id == a.id))
            .count()
    }

    /// The line of the first agent `cat` does not have yet that has no
    /// `name` (`Some(None)` when its line is unknown).
    fn unnamed_new(&self, cat: &AgentCatalog) -> Option<Option<u32>> {
        self.agents
            .iter()
            .find(|a| a.name.is_none() && !cat.agents.iter().any(|have| have.id == a.id))
            .map(|a| a.line)
    }
}

#[derive(Debug)]
struct FileAgent {
    /// Where its `[[agent]]` table starts.
    line: Option<u32>,
    id: String,
    name: Option<String>,
    product: Option<String>,
    executables: Vec<Pattern>,
    names: Vec<Vec<u8>>,
    scripts: Vec<Pattern>,
    signatures: Vec<Signature>,
    markers: Vec<String>,
    install_trees: Vec<InstallTree>,
    code_selecting_env: Vec<String>,
}

impl FileAgent {
    /// Whether it sets a key only the builtin catalog may set
    /// ([`CatalogErrorKind::BuiltinOnly`]).
    fn has_builtin_only(&self) -> bool {
        !self.install_trees.is_empty() || !self.code_selecting_env.is_empty()
    }

    /// Whether an `executables` pattern ends in one of `interpreters`, or
    /// a signature's identifier is one ([`CatalogErrorKind::RuntimeIdentity`]).
    fn names_an_interpreter(&self, interpreters: &[Vec<u8>]) -> bool {
        let is_interpreter = |n: &[u8]| interpreters.iter().any(|i| interpreter_name(n, i));
        self.executables.iter().any(|p| match p.0.last() {
            Some(Component::Name(n)) => is_interpreter(n),
            _ => false,
        }) || self
            .signatures
            .iter()
            .any(|s| is_interpreter(s.identifier.as_bytes()))
    }
}

/// Whether `name` (an executable's file name, a command name or
/// `argv[0]`'s last component) is interpreter `interp`'s: `interp` itself,
/// or `interp` followed by a version, groups of digits joined by dots, the
/// first after a dot when `interp` ends in a digit (`python3.16`,
/// `python3.9`, `node22`), which may end in CPython's ABI
/// flags ([`ABI_FLAGS`], each at most once: `python3.14t`, a free-threaded
/// build; `python3.13d`, a debug build; `python3.13td`; `python3.7m`). No
/// list holds every version and build an interpreter is installed under,
/// and a name it missed would neither have its script read (an agent it
/// runs unseen) nor be refused as an identity
/// ([`CatalogErrorKind::RuntimeIdentity`]) or as an executable match
/// ([`AgentCatalog::classify`]).
fn interpreter_name(name: &[u8], interp: &[u8]) -> bool {
    let Some(rest) = name.strip_prefix(interp) else {
        return false;
    };
    if rest.is_empty() {
        return true;
    }
    let version = rest.len()
        - rest
            .iter()
            .rev()
            .take_while(|b| b.is_ascii_alphabetic())
            .count();
    let (version, flags) = rest.split_at(version);
    // A name that ends in a digit goes on with its own version
    // (`python3` and `.9`).
    let version = match interp.last() {
        Some(d) if d.is_ascii_digit() => version.strip_prefix(b".").unwrap_or(version),
        _ => version,
    };
    !version.is_empty()
        && version
            .split(|b| *b == b'.')
            .all(|group| !group.is_empty() && group.iter().all(u8::is_ascii_digit))
        && flags.iter().all(|f| ABI_FLAGS.contains(f))
        && flags
            .iter()
            .enumerate()
            .all(|(k, f)| !flags[..k].contains(f))
}

/// CPython's ABI flags, which its executables' names end in after the
/// version (`sys.abiflags`): `t` free-threaded (3.13 and later), `d` a
/// debug build, `m` pymalloc (up to 3.7), `u` wide Unicode (up to 3.2).
const ABI_FLAGS: &[u8] = b"tdmu";

/// Parses the builtin catalog: [`parse_catalog`], and no `executables`
/// pattern or signature may name one of its interpreters
/// ([`CatalogErrorKind::RuntimeIdentity`]): a builtin match on the
/// executable roots grants above the caller's session and may be a
/// standing identity, and an interpreter's path or signature names
/// whatever script it runs.
fn parse_builtin(bytes: &[u8]) -> Result<CatalogFile, CatalogError> {
    let file = parse_catalog(bytes)?;
    if let Some(a) = file
        .agents
        .iter()
        .find(|a| a.names_an_interpreter(&file.interpreters))
    {
        return Err(CatalogError {
            kind: CatalogErrorKind::RuntimeIdentity,
            line: a.line,
        });
    }
    Ok(file)
}

/// Line numbers for byte offsets into a file.
struct Lines<'a>(&'a [u8]);

impl Lines<'_> {
    fn at(&self, offset: usize) -> u32 {
        let end = offset.min(self.0.len());
        let n = self.0[..end].iter().filter(|&&b| b == b'\n').count();
        u32::try_from(n).unwrap_or(u32::MAX).saturating_add(1)
    }

    fn key(&self, table: &dyn TableLike, key: &str) -> Option<u32> {
        let span = table.key(key)?.span()?;
        Some(self.at(span.start))
    }

    fn err(&self, kind: CatalogErrorKind, line: Option<u32>) -> CatalogError {
        CatalogError { kind, line }
    }
}

/// Parses one catalog file. Whether an agent without `name` is new, which
/// is refused, depends on the catalog it joins: [`AgentCatalog::load`]
/// checks. The builtin file names every agent (a test checks it).
fn parse_catalog(bytes: &[u8]) -> Result<CatalogFile, CatalogError> {
    if bytes.len() > MAX_CATALOG_FILE {
        return Err(CatalogErrorKind::TooLarge.into());
    }
    let lines = Lines(bytes);
    let text = std::str::from_utf8(bytes)
        .map_err(|e| lines.err(CatalogErrorKind::NotUtf8, Some(lines.at(e.valid_up_to()))))?;
    let doc = Document::parse(text).map_err(|e| {
        // Classified by its fixed description; the message itself quotes
        // the source and is dropped.
        let kind = if e.message().starts_with("duplicate key") {
            CatalogErrorKind::DuplicateKey
        } else {
            CatalogErrorKind::Syntax
        };
        lines.err(kind, e.span().map(|s| lines.at(s.start)))
    })?;
    let mut file = CatalogFile {
        interpreters: Vec::new(),
        agents: Vec::new(),
    };
    let root = doc.as_table();
    for (key, item) in root.iter() {
        let line = lines.key(root, key);
        match key {
            "interpreters" => {
                for s in strings(&lines, item, line)? {
                    let ok = !s.is_empty()
                        && s.len() <= 64
                        && s != "."
                        && s != ".."
                        && !s.contains(['/', '*'])
                        && !s.chars().any(char::is_control);
                    if !ok {
                        return Err(lines.err(CatalogErrorKind::InvalidInterpreter, line));
                    }
                    file.interpreters.push(s.as_bytes().to_vec());
                }
            }
            "agent" => {
                let Item::ArrayOfTables(tables) = item else {
                    return Err(lines.err(CatalogErrorKind::WrongType, line));
                };
                if tables.len() > MAX_AGENTS_PER_FILE {
                    return Err(lines.err(CatalogErrorKind::TooMany, line));
                }
                for t in tables.iter() {
                    let at = t.span().map(|s| lines.at(s.start)).or(line);
                    let a = agent(&lines, t, at)?;
                    if file.agents.iter().any(|b| b.id == a.id) {
                        return Err(lines.err(CatalogErrorKind::DuplicateId, at));
                    }
                    file.agents.push(a);
                }
            }
            _ => return Err(lines.err(CatalogErrorKind::UnknownKey, line)),
        }
    }
    Ok(file)
}

/// An array of strings, at most [`MAX_LIST`] of them.
fn strings<'a>(
    lines: &Lines<'_>,
    item: &'a Item,
    line: Option<u32>,
) -> Result<Vec<&'a str>, CatalogError> {
    let arr = item
        .as_array()
        .ok_or_else(|| lines.err(CatalogErrorKind::WrongType, line))?;
    if arr.len() > MAX_LIST {
        return Err(lines.err(CatalogErrorKind::TooMany, line));
    }
    arr.iter()
        .map(|v| {
            v.as_str()
                .ok_or_else(|| lines.err(CatalogErrorKind::WrongType, line))
        })
        .collect()
}

fn valid_id(s: &str) -> bool {
    let b = s.as_bytes();
    !b.is_empty()
        && b.len() <= 32
        && b.iter()
            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || *c == b'-')
        && b.first() != Some(&b'-')
        && b.last() != Some(&b'-')
}

/// A 10-character Apple Team ID: uppercase ASCII letters and digits.
fn valid_team(s: &str) -> bool {
    s.len() == 10
        && s.bytes()
            .all(|c| c.is_ascii_uppercase() || c.is_ascii_digit())
}

/// A name a process goes by (`names`): 1 to 64 bytes, without `/`, and
/// without control or invisible characters; spaces are allowed (a process
/// title such as `Kimi Code`).
fn valid_agent_name(s: &str) -> bool {
    s.len() <= MAX_NAME_BYTES && s != "." && s != ".." && !s.contains('/') && valid_project_name(s)
}

/// A signing identifier: printable ASCII without spaces, 1 to 128 bytes.
fn valid_identifier(s: &str) -> bool {
    !s.is_empty() && s.len() <= 128 && s.bytes().all(|c| c.is_ascii_graphic())
}

fn agent(
    lines: &Lines<'_>,
    t: &toml_edit::Table,
    at: Option<u32>,
) -> Result<FileAgent, CatalogError> {
    let mut a = FileAgent {
        line: at,
        id: String::new(),
        name: None,
        product: None,
        executables: Vec::new(),
        names: Vec::new(),
        scripts: Vec::new(),
        signatures: Vec::new(),
        markers: Vec::new(),
        install_trees: Vec::new(),
        code_selecting_env: Vec::new(),
    };
    for (key, item) in t.iter() {
        let line = lines.key(t, key).or(at);
        let wrong = || lines.err(CatalogErrorKind::WrongType, line);
        match key {
            "id" => {
                let s = item.as_str().ok_or_else(wrong)?;
                if !valid_id(s) {
                    return Err(lines.err(CatalogErrorKind::InvalidId, line));
                }
                a.id = s.to_owned();
            }
            "name" => {
                let s = item.as_str().ok_or_else(wrong)?;
                if s.len() > MAX_NAME || !valid_project_name(s) {
                    return Err(lines.err(CatalogErrorKind::InvalidName, line));
                }
                a.name = Some(s.to_owned());
            }
            "product" => {
                let s = item.as_str().ok_or_else(wrong)?;
                if !valid_id(s) {
                    return Err(lines.err(CatalogErrorKind::InvalidId, line));
                }
                a.product = Some(s.to_owned());
            }
            "install_trees" => {
                for s in strings(lines, item, line)? {
                    a.install_trees
                        .push(InstallTree::parse(s).ok_or_else(|| {
                            lines.err(CatalogErrorKind::InvalidInstallTree, line)
                        })?);
                }
            }
            "executables" | "scripts" => {
                let mut v = Vec::new();
                for s in strings(lines, item, line)? {
                    v.push(
                        Pattern::parse(s)
                            .ok_or_else(|| lines.err(CatalogErrorKind::InvalidPattern, line))?,
                    );
                }
                if key == "executables" {
                    a.executables = v;
                } else {
                    a.scripts = v;
                }
            }
            "signatures" => {
                let arr = item.as_array().ok_or_else(wrong)?;
                if arr.len() > MAX_LIST {
                    return Err(lines.err(CatalogErrorKind::TooMany, line));
                }
                for v in arr.iter() {
                    a.signatures.push(signature(lines, v, line)?);
                }
            }
            "markers" | "code_selecting_env" => {
                let mut v = Vec::new();
                for s in strings(lines, item, line)? {
                    if !EnvName::valid(s.as_bytes()) {
                        return Err(lines.err(CatalogErrorKind::InvalidMarker, line));
                    }
                    v.push(s.to_owned());
                }
                if key == "markers" {
                    a.markers = v;
                } else {
                    a.code_selecting_env = v;
                }
            }
            "names" => {
                for s in strings(lines, item, line)? {
                    if !valid_agent_name(s) {
                        return Err(lines.err(CatalogErrorKind::InvalidAgentName, line));
                    }
                    a.names.push(s.as_bytes().to_vec());
                }
            }
            _ => return Err(lines.err(CatalogErrorKind::UnknownKey, line)),
        }
    }
    if a.id.is_empty() {
        return Err(lines.err(CatalogErrorKind::MissingKey, at));
    }
    if a.executables.is_empty()
        && a.names.is_empty()
        && a.scripts.is_empty()
        && a.signatures.is_empty()
        && a.markers.is_empty()
    {
        return Err(lines.err(CatalogErrorKind::EmptyAgent, at));
    }
    Ok(a)
}

fn signature(lines: &Lines<'_>, v: &Value, line: Option<u32>) -> Result<Signature, CatalogError> {
    let invalid = || lines.err(CatalogErrorKind::InvalidSignature, line);
    let t = v.as_inline_table().ok_or_else(invalid)?;
    let mut identifier = None;
    let mut team = None;
    for (key, v) in t.iter() {
        let s = v.as_str().ok_or_else(invalid)?;
        match key {
            "identifier" if valid_identifier(s) => identifier = Some(s.to_owned()),
            "team" if valid_team(s) => team = Some(s.to_owned()),
            _ => return Err(invalid()),
        }
    }
    Ok(Signature {
        identifier: identifier.ok_or_else(invalid)?,
        team,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn patterns_match_path_suffixes() {
        let p = Pattern::parse("claude/versions/*").unwrap();
        assert!(p.matches(b"/home/u/.local/share/claude/versions/2.1.112"));
        assert!(!p.matches(b"/home/u/.local/share/claude/versions"));
        assert!(!p.matches(b"/opt/claude/other/2.1"));
        let p = Pattern::parse("claude").unwrap();
        assert!(p.matches(b"claude"));
        assert!(p.matches(b"./claude"));
        assert!(p.matches(b"/usr/local/bin/claude"));
        assert!(!p.matches(b"/usr/local/bin/claude2"));
        assert!(!p.matches(b"/usr/local/bin/Claude"));
        assert!(!p.matches(b""));
        let p = Pattern::parse("@anthropic-ai/claude-code/cli.js").unwrap();
        assert!(p.matches(b"/opt/lib/node_modules/@anthropic-ai/claude-code/cli.js"));
        assert!(!p.matches(b"/opt/lib/node_modules/@evil/claude-code/cli.js"));
    }

    #[test]
    fn bad_patterns_are_refused() {
        for bad in [
            "", "*", "*/*", "/claude", "claude/", "a//b", "./claude", "a/../b", "cla*de", "a\nb",
        ] {
            assert!(Pattern::parse(bad).is_none(), "{bad:?}");
        }
        assert!(Pattern::parse("a/".repeat(8).trim_end_matches('/')).is_some());
        assert!(Pattern::parse("a/".repeat(9).trim_end_matches('/')).is_none());
        assert!(Pattern::parse(&"a".repeat(257)).is_none());
    }

    /// Install trees: absolute or `~/` paths of names and `*`; an
    /// executable is in one when its path lies strictly below it, every
    /// component compared byte for byte.
    #[test]
    fn install_trees_hold_paths_strictly_below_them() {
        let home = Path::new("/home/u");
        let t = InstallTree::parse("~/.local/share/claude/versions").unwrap();
        assert!(t.contains(
            Path::new("/home/u/.local/share/claude/versions/2.1.280"),
            Some(home)
        ));
        for outside in [
            "/home/u/.local/share/claude/versions",
            "/home/u/.local/share/claude/version/2.1.280",
            "/home/v/.local/share/claude/versions/2.1.280",
            "/home/u/.local/share/claude/versions/../../../bin/claude",
            "/home/u/.local/share/claude/versions/./x",
            "relative/.local/share/claude/versions/x",
            "/tmp/claude",
        ] {
            assert!(!t.contains(Path::new(outside), Some(home)), "{outside}");
        }
        // No home, or a relative one: a ~/ tree holds nothing.
        let inside = Path::new("/home/u/.local/share/claude/versions/2.1.280");
        assert!(!t.contains(inside, None));
        assert!(!t.contains(inside, Some(Path::new("home/u"))));
        // `*` is one component; absolute trees ignore the home directory.
        let t = InstallTree::parse("/opt/*/lib/node_modules/@openai/codex").unwrap();
        assert!(t.contains(
            Path::new("/opt/v22/lib/node_modules/@openai/codex/bin/codex.js"),
            None
        ));
        assert!(!t.contains(
            Path::new("/opt/a/b/lib/node_modules/@openai/codex/bin/codex.js"),
            None
        ));
        // A deleted executable's path keeps its directory.
        let t = InstallTree::parse("/usr/local/bin").unwrap();
        assert!(t.contains(Path::new("/usr/local/bin/copilot (deleted)"), None));
        for bad in [
            "",
            "~",
            "~/",
            "/",
            "relative/path",
            "//x",
            "/a//b",
            "/a/./b",
            "/a/../b",
            "~x/y",
            "/a/b*",
            "/a\nb",
            "~/a/",
        ] {
            assert!(InstallTree::parse(bad).is_none(), "{bad:?}");
        }
        assert!(InstallTree::parse(&format!("/{}", ["a"; 16].join("/"))).is_some());
        assert!(InstallTree::parse(&format!("/{}", ["a"; 17].join("/"))).is_none());
        assert!(InstallTree::parse(&format!("/{}", "a".repeat(256))).is_none());
    }

    /// An interpreter's name, or that name and a version: groups of digits
    /// joined by dots, which may end in CPython's ABI flags (each at most
    /// once). Mutation checked: matching names only exactly fails this
    /// test, and the classification cases of a Python and a node the
    /// interpreters list does not name (tests/agents.rs); so does taking a
    /// version without its ABI flags (the free-threaded and debug builds
    /// here and in tests/agents.rs).
    #[test]
    fn a_versioned_interpreter_name_is_the_interpreter() {
        for (name, interp) in [
            ("node", "node"),
            ("node22", "node"),
            ("python3", "python3"),
            ("python3.9", "python3"),
            ("python3.16", "python3"),
            ("python3.16", "python"),
            ("bun1.3.14", "bun"),
            // Free-threaded (python.org's, `uv python install 3.14t`,
            // Fedora's), debug, both, and the pymalloc builds up to 3.7.
            ("python3.14t", "python3"),
            ("python3.13t", "python"),
            ("python3.13d", "python3"),
            ("python3.13td", "python3"),
            ("python3.7m", "python3"),
            ("python3.7dm", "python3"),
            ("python3t", "python"),
        ] {
            assert!(
                interpreter_name(name.as_bytes(), interp.as_bytes()),
                "{name} {interp}"
            );
        }
        for (name, interp) in [
            ("nodejs", "node"),
            ("nodemon", "node"),
            ("node.", "node"),
            ("node-22", "node"),
            ("python3.16a", "python3"),
            ("Python3", "python"),
            ("pytho", "python"),
            ("", "node"),
            ("bunx", "bun"),
            // ABI flags only after a version, each once, and nothing else.
            ("nodet", "node"),
            ("python3t-config", "python3"),
            ("python3t-config", "python"),
            ("python3.14tt", "python3"),
            ("python3.14x", "python3"),
            ("python3.14-dbg", "python3"),
            ("python3.", "python"),
            ("python3..14", "python3"),
            ("python.3", "python"),
            ("python3.14t.1", "python3"),
        ] {
            assert!(
                !interpreter_name(name.as_bytes(), interp.as_bytes()),
                "{name} {interp}"
            );
        }
    }

    /// The builtin catalog may not name an interpreter as an executable or
    /// by its signature: an interpreter's path or signature names whatever
    /// script it runs, and a builtin match on either roots grants above the
    /// caller's session. A pattern that ends in `*`, or in another name,
    /// passes; an extension may (its matches never root above a session).
    /// Mutation checked: dropping the check lets each bad file load, and
    /// `cursor-agent/versions/*/node`, the entry M2-10 first wrote, is one.
    #[test]
    fn the_builtin_catalog_names_no_interpreter_as_an_identity() {
        let head = "interpreters = [\"node\", \"bun\", \"python3\"]\n[[agent]]\nid = \"a\"\nname = \"A\"\n";
        for bad in [
            "executables = [\"cursor-agent/versions/*/node\"]",
            "executables = [\"bun\"]",
            "executables = [\"tools/node22\"]",
            "executables = [\"tools/python3.14t\"]",
            "signatures = [{ identifier = \"node\", team = \"HX7739G8FX\" }]",
        ] {
            let text = format!("{head}{bad}\n");
            let e = parse_builtin(text.as_bytes()).unwrap_err();
            assert_eq!(
                (e.kind(), e.line()),
                (CatalogErrorKind::RuntimeIdentity, Some(2)),
                "{bad}"
            );
            assert!(parse_catalog(text.as_bytes()).is_ok(), "{bad}");
        }
        for good in [
            "executables = [\"claude/versions/*\"]",
            "executables = [\"node-agent\"]",
            "scripts = [\"x/node\"]",
            "signatures = [{ identifier = \"com.example.node\" }]",
        ] {
            assert!(
                parse_builtin(format!("{head}{good}\n").as_bytes()).is_ok(),
                "{good}"
            );
        }
        assert!(parse_builtin(AGENTS_TOML.as_bytes()).is_ok());
    }

    #[test]
    fn comm_names_allow_for_the_kernels_cut() {
        assert!(comm_names(b"Kimi Code", b"Kimi Code"));
        assert!(comm_names(b"kimi-code-bg-wo", b"kimi-code-bg-worker"));
        assert!(comm_names(b"kimi-code-bg-wor", b"kimi-code-bg-worker"));
        assert!(!comm_names(b"kimi-code-bg", b"kimi-code-bg-worker"));
        assert!(!comm_names(b"", b"x"));
        assert!(!comm_names(b"kimi-code-bg-wo", b"kimi-code-bg-w"));
    }

    #[test]
    fn ids_and_teams() {
        for ok in ["claude-code", "codex", "a", "a1-b2"] {
            assert!(valid_id(ok), "{ok}");
        }
        for bad in ["", "-a", "a-", "A", "a_b", "a b", &"a".repeat(33)] {
            assert!(!valid_id(bad), "{bad}");
        }
        assert!(valid_team("Q6L2SF6YDW"));
        assert!(!valid_team("q6l2sf6ydw"));
        assert!(!valid_team("Q6L2SF6YD"));
    }
}
