//! The agent catalog as compiled in: integrations/agents.toml, byte for
//! byte (SPEC §10a). [`crate::AgentCatalog::builtin`] parses it.
//!
//! Generated by scripts/gen-agents.py from integrations/agents.toml. Do not
//! edit.

/// The contents of integrations/agents.toml.
pub(crate) static AGENTS_TOML: &str = r#"# Known AI coding agents, for caller evidence (SPEC §10a, §10b "Root
# selection"). Format and rules: docs/AGENTS.md.
#
# A process in a caller's ancestry is an agent when its executable, its
# script (under an interpreter) or its macOS code signature matches an entry
# here. A match makes handling stricter (an agent subject, the agent
# barrier, proofs refused); a pattern that misses an agent lets it ride a
# terminal grant. A match on the executable's path or signature also makes
# the agent the root of its grants above the caller's session, covering
# every command it runs, so `executables` must name agents only. A match on
# argv[0], a script or the command name, which a process sets itself, never
# does that. Compiled into the release by scripts/gen-agents.py; users add
# entries under <data>/agents.d/.

# Executables that run scripts. For these, the script arguments are matched
# against each agent's `scripts`.
interpreters = ["node", "nodejs", "bun", "deno"]

[[agent]]
id = "claude-code"
name = "Claude Code"
# The native build: ~/.local/share/claude/versions/<version>, or npm's
# @anthropic-ai/claude-code/bin/claude.exe, run through a `claude` link.
executables = ["claude", "claude.exe", "claude/versions/*"]
# The older npm build: node .../@anthropic-ai/claude-code/cli.js, or a
# `claude` script run through its shebang.
scripts = ["claude", "@anthropic-ai/claude-code/cli.js"]
signatures = [{ team = "Q6L2SF6YDW", identifier = "com.anthropic.claude-code" }]
# Set in the environment of the commands it runs.
markers = ["CLAUDECODE", "CLAUDE_CODE_ENTRYPOINT"]

[[agent]]
id = "codex"
name = "Codex"
# The native binary, also under npm's @openai/codex-<platform>/vendor/.
executables = ["codex"]
# npm's launcher, which starts the native binary.
scripts = ["codex", "@openai/codex/bin/codex.js"]
signatures = [{ team = "2DC432GLL2", identifier = "codex" }]
markers = ["CODEX_THREAD_ID", "CODEX_SANDBOX", "CODEX_SANDBOX_NETWORK_DISABLED"]

[[agent]]
id = "fixture"
name = "EnvCloak test fixture agent"
# crates/envcloak-testkit/src/bin/fixture-agent.rs, which the acceptance
# tests run as an agent, in CI from the release build. Only a program by
# this name matches, and like every executable here it then roots its
# grants above the caller's session (docs/AGENTS.md "Limits").
executables = ["fixture-agent"]
markers = ["ENVCLOAK_FIXTURE_AGENT"]
"#;
