//! The agent catalog: which processes are AI coding agents (SPEC §10a "An
//! ancestor is Claude Code, Codex, Cursor and so on", §10b "Root
//! selection"). The format and the rules are in docs/AGENTS.md.
//!
//! - [`AgentCatalog::builtin`]: `integrations/agents.toml`, compiled in
//!   (`agents_builtin.rs`, generated by scripts/gen-agents.py).
//! - [`AgentCatalog::load`]: the builtin catalog plus the user's extensions,
//!   `<data>/agents.d/*.toml`. Extensions only add: new agents, and more
//!   patterns, signatures, markers and interpreters for existing ones.
//!   Nothing in them removes or narrows a builtin entry. A file that fails
//!   a check is skipped and reported ([`AgentCatalog::problems`]).
//! - [`AgentCatalog::classify`]: the agent a process is, from its
//!   executable (path, `argv[0]` or command name), its script when an
//!   interpreter runs it, or its macOS code signature. Builtin entries are
//!   tried first, and the label says which kind matched
//!   ([`CatalogSource`]) and on what ([`MatchBasis`]).
//!
//! A match labels the process an agent, which only tightens: the caller
//! is an agent subject, the agent barrier applies, and its proofs are
//! refused. One use of a match can widen: an agent runs each command in a
//! session of its own, so a grant for it is rooted at the agent process,
//! above the caller's session (`crate::SubjectEvidence`). Only a builtin
//! match on the executable's path or its code signature
//! ([`AgentLabel::may_root_above_session`]) does that (SPEC §10a). A match
//! on what a process says about itself (`argv[0]`, its script, its command
//! name), or one that needed a user extension, roots a grant no higher
//! than the caller's session leader, so it cannot widen a grant to sibling
//! sessions. That includes a match on arguments read only because an
//! extension names an interpreter: the builtin pass uses arguments only
//! where the builtin catalog alone would read them.
//!
//! So a builtin `executables` pattern must name agents only: one that also
//! matched a terminal multiplexer's executable would root grants at it.
//! Errors are value-free: a kind and a line.

use std::ffi::{OsStr, OsString};
use std::fs::{File, OpenOptions};
use std::io::{self, Read};
use std::os::unix::ffi::OsStrExt;
use std::os::unix::fs::{MetadataExt, OpenOptionsExt};
use std::path::Path;

use envcloak_sys::{Argv, ProcInfo};
use toml_edit::{Document, Item, TableLike, Value};

use crate::agents_builtin::AGENTS_TOML;
use crate::manifest::valid_project_name;
use crate::names::EnvName;

/// The directory under the data directory that holds extensions.
pub const AGENTS_DIR: &str = "agents.d";
/// The largest catalog file accepted, in bytes.
pub const MAX_CATALOG_FILE: usize = 64 * 1024;
/// Extension files read; the rest (in name order) are reported and
/// skipped.
pub const MAX_EXTENSION_FILES: usize = 16;
/// Agents one file may define.
const MAX_AGENTS_PER_FILE: usize = 64;
/// Agents in the merged catalog.
const MAX_AGENTS: usize = 256;
/// Entries in any one list (`executables`, `scripts`, `signatures`,
/// `markers`, `interpreters`) of one file.
const MAX_LIST: usize = 32;
/// Components in a pattern.
const MAX_COMPONENTS: usize = 8;
/// Bytes in a pattern.
const MAX_PATTERN: usize = 256;
/// Bytes in an agent's display name.
const MAX_NAME: usize = 64;
/// How many arguments of an interpreter are looked at for its script:
/// the first few that are not options, among the first few in all, which
/// are all the kernel's view keeps after `argv[0]`
/// ([`envcloak_sys::MAX_ARGV`]).
const SCRIPT_ARGS: usize = 3;
const SCRIPT_ARGS_SCANNED: usize = envcloak_sys::MAX_ARGV - 1;

/// Where a catalog entry came from.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum CatalogSource {
    /// `integrations/agents.toml`, shipped in the release.
    Builtin,
    /// A file in `<data>/agents.d/`.
    Extension,
}

/// What a match rests on (SPEC §10a: an executable's identity is
/// evidence; argv is caller-asserted).
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum MatchBasis {
    /// The executable's path as the kernel reports it, or the macOS code
    /// signature the kernel validated when it started.
    Executable,
    /// What the process says about itself, which it can set: its
    /// `argv[0]`, an interpreter's script argument, or its command name
    /// (Linux: `prctl(PR_SET_NAME)`, or the name of a link it was run
    /// through). Also an environment marker's label.
    Asserted,
}

/// What an agent is shown as. Display only (SPEC §10b `kind:
/// agent(label)`), except that [`AgentLabel::may_root_above_session`]
/// limits where a grant may be rooted.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct AgentLabel {
    /// The catalog id: `claude-code`, `codex`, ...
    pub id: String,
    /// The display name: `Claude Code`, ...
    pub name: String,
    /// Whether a builtin entry matched, or only an extension did.
    pub source: CatalogSource,
    /// Whether the match rests on the executable, or only on what the
    /// process says about itself.
    pub basis: MatchBasis,
}

impl AgentLabel {
    /// Whether this match may root a grant above the caller's session: a
    /// builtin entry matched the executable's path or its code signature.
    /// Any other match roots a grant no higher than the session rules
    /// would (SPEC §10b "Root selection").
    pub fn may_root_above_session(&self) -> bool {
        self.source == CatalogSource::Builtin && self.basis == MatchBasis::Executable
    }
}

/// What is wrong with a catalog file. Every message is fixed text.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum CatalogErrorKind {
    TooLarge,
    NotUtf8,
    /// Not TOML.
    Syntax,
    DuplicateKey,
    UnknownKey,
    WrongType,
    /// An agent without `id`, or a new agent without `name`.
    MissingKey,
    InvalidId,
    InvalidName,
    InvalidPattern,
    InvalidInterpreter,
    InvalidSignature,
    InvalidMarker,
    /// One file defines an id twice.
    DuplicateId,
    /// An agent that matches nothing: no executables, scripts, signatures
    /// or markers.
    EmptyAgent,
    /// More entries than a list, a file or the catalog may hold.
    TooMany,
    /// `agents.d` is a symlink, not a directory, another user's, or
    /// writable by group or others.
    UnsafeDirectory,
    /// The file is a symlink.
    Symlink,
    NotRegularFile,
    /// Owned by another user.
    NotOwned,
    /// Writable by group or others.
    Writable,
    /// Another I/O error.
    Io(io::ErrorKind),
}

impl CatalogErrorKind {
    fn message(self) -> &'static str {
        use CatalogErrorKind as K;
        match self {
            K::TooLarge => "the catalog file is larger than 64 KiB",
            K::NotUtf8 => "the catalog file is not UTF-8",
            K::Syntax => "not valid TOML",
            K::DuplicateKey => "a key is defined twice",
            K::UnknownKey => "unknown key",
            K::WrongType => "a value has the wrong type",
            K::MissingKey => "an agent needs an id, and a new agent a name",
            K::InvalidId => {
                "invalid agent id: lowercase ASCII letters, digits and inner -, at most 32 bytes"
            }
            K::InvalidName => {
                "invalid agent name: 1 to 64 bytes, without control or invisible characters"
            }
            K::InvalidPattern => {
                "invalid pattern: path components separated by /, each a name or *, with at least \
                 one name, at most 8 components and 256 bytes"
            }
            K::InvalidInterpreter => "invalid interpreter: one file name, without / or *",
            K::InvalidSignature => {
                "invalid signature: { identifier = \"<signing id>\", team = \"<10-character Team \
                 ID>\" }, team optional"
            }
            K::InvalidMarker => {
                "invalid marker: an environment variable name (an ASCII letter or _, then letters, \
                 digits or _)"
            }
            K::DuplicateId => "an agent id is defined twice in one file",
            K::EmptyAgent => "an agent must list executables, scripts, signatures or markers",
            K::TooMany => "too many entries",
            K::UnsafeDirectory => {
                "agents.d must be a directory of this user, not a symlink, and not writable by \
                 group or others"
            }
            K::Symlink => "the catalog file is a symlink, which is refused",
            K::NotRegularFile => "the catalog file is not a regular file",
            K::NotOwned => "the catalog file is owned by another user",
            K::Writable => "the catalog file is writable by group or others",
            K::Io(_) => "cannot read the catalog file",
        }
    }
}

/// A catalog error: a kind and, for content errors, the line.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct CatalogError {
    kind: CatalogErrorKind,
    line: Option<u32>,
}

impl CatalogError {
    pub fn kind(&self) -> CatalogErrorKind {
        self.kind
    }

    pub fn line(&self) -> Option<u32> {
        self.line
    }
}

impl From<CatalogErrorKind> for CatalogError {
    fn from(kind: CatalogErrorKind) -> Self {
        CatalogError { kind, line: None }
    }
}

impl core::fmt::Display for CatalogError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        if let Some(line) = self.line {
            write!(f, "line {line}: ")?;
        }
        f.write_str(self.kind.message())?;
        if let CatalogErrorKind::Io(k) = self.kind {
            write!(f, " ({k})")?;
        }
        Ok(())
    }
}

impl std::error::Error for CatalogError {}

/// An extension file that was skipped, or an `agents.d` that was not read
/// (`file` is then `agents.d`).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CatalogProblem {
    /// The file's name in `agents.d`.
    pub file: OsString,
    pub error: CatalogError,
}

/// One path component of a pattern.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
enum Component {
    Name(Vec<u8>),
    /// `*`: any one component.
    Any,
}

/// A path suffix: `claude`, `claude/versions/*`,
/// `@anthropic-ai/claude-code/cli.js`. It matches a path whose last
/// components are these, `*` standing for any one.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
struct Pattern(Vec<Component>);

impl Pattern {
    fn parse(s: &str) -> Option<Pattern> {
        if s.is_empty() || s.len() > MAX_PATTERN {
            return None;
        }
        let mut out = Vec::new();
        for c in s.split('/') {
            if c.is_empty() || c == "." || c == ".." || c.chars().any(char::is_control) {
                return None;
            }
            if c == "*" {
                out.push(Component::Any);
            } else if c.contains('*') {
                return None;
            } else {
                out.push(Component::Name(c.as_bytes().to_vec()));
            }
        }
        let named = out.iter().any(|c| matches!(c, Component::Name(_)));
        (named && out.len() <= MAX_COMPONENTS).then_some(Pattern(out))
    }

    /// Whether `path`'s last components are this pattern's. Empty and `.`
    /// components of `path` are skipped, so `./claude` and `claude/` are
    /// `claude`.
    fn matches(&self, path: &[u8]) -> bool {
        let comps: Vec<&[u8]> = path
            .split(|b| *b == b'/')
            .filter(|c| !c.is_empty() && *c != b".")
            .collect();
        if comps.len() < self.0.len() {
            return false;
        }
        let tail = &comps[comps.len() - self.0.len()..];
        self.0.iter().zip(tail).all(|(p, c)| match p {
            Component::Any => true,
            Component::Name(n) => n.as_slice() == *c,
        })
    }
}

/// A macOS code signature an agent is signed with.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
struct Signature {
    identifier: String,
    /// `None`: any team, or none.
    team: Option<String>,
}

/// One agent: its id, its name, and what identifies it, each entry tagged
/// with where it came from.
#[derive(Debug, Clone)]
struct Agent {
    id: String,
    name: String,
    executables: Vec<(Pattern, CatalogSource)>,
    scripts: Vec<(Pattern, CatalogSource)>,
    signatures: Vec<(Signature, CatalogSource)>,
    markers: Vec<(String, CatalogSource)>,
}

/// The known agents. See the module documentation.
#[derive(Debug, Clone)]
pub struct AgentCatalog {
    agents: Vec<Agent>,
    interpreters: Vec<(Vec<u8>, CatalogSource)>,
    problems: Vec<CatalogProblem>,
}

impl AgentCatalog {
    /// The catalog compiled into this build.
    ///
    /// # Panics
    /// Never in a tested build: the `agents` test parses it.
    pub fn builtin() -> Self {
        let mut cat = AgentCatalog {
            agents: Vec::new(),
            interpreters: Vec::new(),
            problems: Vec::new(),
        };
        let file = parse_catalog(AGENTS_TOML.as_bytes()).expect("the builtin agent catalog parses");
        cat.merge(file, CatalogSource::Builtin);
        cat
    }

    /// The text [`AgentCatalog::builtin`] parses: integrations/agents.toml
    /// as compiled in.
    pub fn builtin_source() -> &'static str {
        AGENTS_TOML
    }

    /// The builtin catalog plus the extensions in `<data_dir>/agents.d/`.
    /// A missing directory is no extensions; an unsafe one, or a file that
    /// fails a check, is reported in [`AgentCatalog::problems`] and
    /// skipped.
    pub fn load(data_dir: &Path) -> Self {
        let mut cat = Self::builtin();
        let dir_path = data_dir.join(AGENTS_DIR);
        let dir = match OpenOptions::new()
            .read(true)
            .custom_flags(libc::O_DIRECTORY | libc::O_NOFOLLOW | libc::O_CLOEXEC)
            .open(&dir_path)
        {
            Ok(d) => d,
            Err(e) if e.kind() == io::ErrorKind::NotFound => return cat,
            Err(e) => {
                let kind = match e.raw_os_error() {
                    Some(libc::ELOOP | libc::ENOTDIR) => CatalogErrorKind::UnsafeDirectory,
                    _ => CatalogErrorKind::Io(e.kind()),
                };
                cat.problem(OsStr::new(AGENTS_DIR), kind.into());
                return cat;
            }
        };
        let trusted = dir.metadata().is_ok_and(|m| {
            m.is_dir() && m.uid() == envcloak_sys::effective_uid() && m.mode() & 0o022 == 0
        });
        if !trusted {
            cat.problem(
                OsStr::new(AGENTS_DIR),
                CatalogErrorKind::UnsafeDirectory.into(),
            );
            return cat;
        }
        // The listing goes by path; each file is then opened through the
        // checked directory's handle, so only files in it are read.
        let mut names: Vec<OsString> = match std::fs::read_dir(&dir_path) {
            Ok(entries) => entries
                .filter_map(Result::ok)
                .map(|e| e.file_name())
                .filter(|n| {
                    let b = n.as_bytes();
                    b.ends_with(b".toml") && !b.starts_with(b".")
                })
                .collect(),
            Err(e) => {
                cat.problem(
                    OsStr::new(AGENTS_DIR),
                    CatalogErrorKind::Io(e.kind()).into(),
                );
                return cat;
            }
        };
        names.sort();
        for (i, name) in names.iter().enumerate() {
            if i >= MAX_EXTENSION_FILES {
                cat.problem(name, CatalogErrorKind::TooMany.into());
                continue;
            }
            match read_extension(&dir, name).and_then(|b| parse_catalog(&b)) {
                Ok(file) if cat.agents.len() + file.new_ids(&cat) > MAX_AGENTS => {
                    cat.problem(name, CatalogErrorKind::TooMany.into());
                }
                Ok(file) if file.unnamed_new(&cat).is_some() => {
                    let line = file.unnamed_new(&cat);
                    cat.problem(
                        name,
                        CatalogError {
                            kind: CatalogErrorKind::MissingKey,
                            line: line.flatten(),
                        },
                    );
                }
                Ok(file) => cat.merge(file, CatalogSource::Extension),
                Err(e) => cat.problem(name, e),
            }
        }
        cat
    }

    fn problem(&mut self, file: &OsStr, error: CatalogError) {
        self.problems.push(CatalogProblem {
            file: file.to_owned(),
            error,
        });
    }

    /// The extension files skipped, and why.
    pub fn problems(&self) -> &[CatalogProblem] {
        &self.problems
    }

    /// The ids of the known agents, builtin first.
    pub fn ids(&self) -> impl Iterator<Item = &str> {
        self.agents.iter().map(|a| a.id.as_str())
    }

    /// Every environment marker the catalog knows, for the CLI's claims
    /// ([`crate::Claims::from_env`]).
    pub fn markers(&self) -> impl Iterator<Item = &str> {
        self.agents
            .iter()
            .flat_map(|a| a.markers.iter().map(|(m, _)| m.as_str()))
    }

    /// The agent that sets marker `name`, if the catalog knows one. A
    /// marker is a claim: the label's basis is [`MatchBasis::Asserted`].
    pub fn agent_for_marker(&self, name: &str) -> Option<AgentLabel> {
        self.agents.iter().find_map(|a| {
            a.markers
                .iter()
                .find(|(m, _)| m == name)
                .map(|(_, source)| label(a, *source, MatchBasis::Asserted))
        })
    }

    /// Whether `p` looks like an interpreter by its executable or command
    /// name, or by `argv[0]` when `argv` is given. Extension interpreters
    /// count only when `extensions` is set.
    fn interpreter(&self, p: &ProcInfo, extensions: bool, argv: Option<&Argv>) -> bool {
        let names = [
            p.exe
                .as_ref()
                .and_then(|e| e.path.file_name())
                .map(OsStr::as_bytes),
            Some(p.comm.as_bytes()),
            argv.and_then(Argv::first)
                .map(|a| last_component(a.as_bytes())),
        ];
        self.interpreters
            .iter()
            .filter(|(_, s)| extensions || *s == CatalogSource::Builtin)
            .any(|(i, _)| names.iter().flatten().any(|n| *n == i.as_slice()))
    }

    /// Whether the catalog reads `p`'s arguments: its executable is hidden
    /// (so `argv[0]` stands in for it), or its executable or command name
    /// is an interpreter (so its script decides). Extension interpreters
    /// count only when `extensions` is set.
    fn reads_argv(&self, p: &ProcInfo, extensions: bool) -> bool {
        p.exe.is_none() || self.interpreter(p, extensions, None)
    }

    /// Whether classifying `p` needs its arguments: its executable is
    /// hidden (so `argv[0]` stands in for it), or it runs an interpreter,
    /// builtin or from an extension (so its script decides).
    pub fn needs_argv(&self, p: &ProcInfo) -> bool {
        self.reads_argv(p, true)
    }

    /// The agent `p` is, if any. Builtin entries are tried first; the
    /// label's [`AgentLabel::source`] says whether one matched. Within
    /// each pass, a match on the executable's path or its signature is
    /// preferred to one on what the process says about itself; the label's
    /// [`AgentLabel::basis`] says which it was.
    ///
    /// `argv[0]`, the script and the command name are the process's own
    /// word (SPEC §10a "Environment markers and argv": caller-asserted), so
    /// a match on them is [`MatchBasis::Asserted`], which roots no grant
    /// above the caller's session (review finding F-37).
    ///
    /// Each pass uses `p`'s arguments only where that pass's catalog would
    /// read them itself ([`AgentCatalog::needs_argv`] reads them for either
    /// pass). Arguments read only because an extension names an
    /// interpreter are not builtin evidence: a match on them (its `argv[0]`
    /// or its script, even against a builtin pattern) is an extension
    /// match (review finding F-36).
    pub fn classify(&self, p: &ProcInfo) -> Option<AgentLabel> {
        let path = p
            .exe
            .as_ref()
            .map(|e| e.path.as_os_str().as_bytes())
            .filter(|n| !n.is_empty());
        let signature = p.exe.as_ref().and_then(|e| e.signature.as_ref());
        for source in [CatalogSource::Builtin, CatalogSource::Extension] {
            let extensions = source == CatalogSource::Extension;
            let argv = if self.reads_argv(p, extensions) {
                p.argv.as_ref()
            } else {
                None
            };
            let interpreter = self.interpreter(p, extensions, argv);
            let scripts = if interpreter {
                script_args(argv)
            } else {
                Vec::new()
            };
            let said: Vec<&[u8]> = [
                Some(p.comm.as_bytes()),
                argv.and_then(Argv::first).map(OsStr::as_bytes),
            ]
            .into_iter()
            .flatten()
            .filter(|n| !n.is_empty())
            .collect();
            let counts = |s: &CatalogSource| extensions || *s == CatalogSource::Builtin;
            let by_executable = |a: &Agent| {
                let by_path = path.is_some_and(|path| {
                    a.executables
                        .iter()
                        .filter(|(_, s)| counts(s))
                        .any(|(pat, _)| pat.matches(path))
                });
                by_path
                    || signature.is_some_and(|sig| {
                        a.signatures
                            .iter()
                            .filter(|(_, s)| counts(s))
                            .any(|(want, _)| {
                                want.identifier == sig.identifier
                                    && want
                                        .team
                                        .as_ref()
                                        .is_none_or(|t| sig.team_id.as_ref() == Some(t))
                            })
                    })
            };
            let by_assertion = |a: &Agent| {
                a.executables
                    .iter()
                    .filter(|(_, s)| counts(s))
                    .any(|(pat, _)| said.iter().any(|n| pat.matches(n)))
                    || a.scripts
                        .iter()
                        .filter(|(_, s)| counts(s))
                        .any(|(pat, _)| scripts.iter().any(|n| pat.matches(n)))
            };
            if let Some(a) = self.agents.iter().find(|a| by_executable(a)) {
                return Some(label(a, source, MatchBasis::Executable));
            }
            if let Some(a) = self.agents.iter().find(|a| by_assertion(a)) {
                return Some(label(a, source, MatchBasis::Asserted));
            }
        }
        None
    }

    fn merge(&mut self, file: CatalogFile, source: CatalogSource) {
        for i in file.interpreters {
            if !self.interpreters.iter().any(|(have, _)| *have == i) {
                self.interpreters.push((i, source));
            }
        }
        for new in file.agents {
            let tag = |v: Vec<Pattern>| v.into_iter().map(|p| (p, source)).collect::<Vec<_>>();
            match self.agents.iter_mut().find(|a| a.id == new.id) {
                Some(a) => {
                    a.executables.extend(tag(new.executables));
                    a.scripts.extend(tag(new.scripts));
                    a.signatures
                        .extend(new.signatures.into_iter().map(|s| (s, source)));
                    a.markers
                        .extend(new.markers.into_iter().map(|m| (m, source)));
                }
                None => self.agents.push(Agent {
                    // A new agent always has a name: `load` refuses an
                    // extension without one, and the builtin file names each.
                    name: new.name.unwrap_or_else(|| new.id.clone()),
                    id: new.id,
                    executables: tag(new.executables),
                    scripts: tag(new.scripts),
                    signatures: new.signatures.into_iter().map(|s| (s, source)).collect(),
                    markers: new.markers.into_iter().map(|m| (m, source)).collect(),
                }),
            }
        }
    }
}

fn label(a: &Agent, source: CatalogSource, basis: MatchBasis) -> AgentLabel {
    AgentLabel {
        id: a.id.clone(),
        name: a.name.clone(),
        source,
        basis,
    }
}

fn last_component(path: &[u8]) -> &[u8] {
    path.rsplit(|b| *b == b'/')
        .find(|c| !c.is_empty())
        .unwrap_or(path)
}

/// The arguments of an interpreter that may name its script: the first
/// [`SCRIPT_ARGS`] that are not options, among the first
/// [`SCRIPT_ARGS_SCANNED`] after `argv[0]`. Borrowed from the wiped
/// [`Argv`], never copied.
fn script_args(argv: Option<&Argv>) -> Vec<&[u8]> {
    let Some(argv) = argv else {
        return Vec::new();
    };
    argv.iter()
        .skip(1)
        .take(SCRIPT_ARGS_SCANNED)
        .map(OsStr::as_bytes)
        .filter(|a| !a.is_empty() && !a.starts_with(b"-"))
        .take(SCRIPT_ARGS)
        .collect()
}

/// Opens `name` in the checked `agents.d` handle and reads it, after
/// `fstat` shows a regular file of this user that group and others cannot
/// write, no larger than [`MAX_CATALOG_FILE`].
fn read_extension(dir: &File, name: &OsStr) -> Result<Vec<u8>, CatalogError> {
    let file = envcloak_sys::open_beneath(dir, name).map_err(|e| {
        if e.raw_os_error() == Some(libc::ELOOP) {
            CatalogErrorKind::Symlink
        } else {
            CatalogErrorKind::Io(e.kind())
        }
    })?;
    let m = file
        .metadata()
        .map_err(|e| CatalogErrorKind::Io(e.kind()))?;
    if !m.file_type().is_file() {
        return Err(CatalogErrorKind::NotRegularFile.into());
    }
    if m.uid() != envcloak_sys::effective_uid() {
        return Err(CatalogErrorKind::NotOwned.into());
    }
    if m.mode() & 0o022 != 0 {
        return Err(CatalogErrorKind::Writable.into());
    }
    let mut bytes = Vec::new();
    file.take(MAX_CATALOG_FILE as u64 + 1)
        .read_to_end(&mut bytes)
        .map_err(|e| CatalogErrorKind::Io(e.kind()))?;
    if bytes.len() > MAX_CATALOG_FILE {
        return Err(CatalogErrorKind::TooLarge.into());
    }
    Ok(bytes)
}

/// One parsed catalog file.
#[derive(Debug)]
struct CatalogFile {
    interpreters: Vec<Vec<u8>>,
    agents: Vec<FileAgent>,
}

impl CatalogFile {
    /// How many of this file's agents `cat` does not have yet.
    fn new_ids(&self, cat: &AgentCatalog) -> usize {
        self.agents
            .iter()
            .filter(|a| !cat.agents.iter().any(|have| have.id == a.id))
            .count()
    }

    /// The line of the first agent `cat` does not have yet that has no
    /// `name` (`Some(None)` when its line is unknown).
    fn unnamed_new(&self, cat: &AgentCatalog) -> Option<Option<u32>> {
        self.agents
            .iter()
            .find(|a| a.name.is_none() && !cat.agents.iter().any(|have| have.id == a.id))
            .map(|a| a.line)
    }
}

#[derive(Debug)]
struct FileAgent {
    /// Where its `[[agent]]` table starts.
    line: Option<u32>,
    id: String,
    name: Option<String>,
    executables: Vec<Pattern>,
    scripts: Vec<Pattern>,
    signatures: Vec<Signature>,
    markers: Vec<String>,
}

/// Line numbers for byte offsets into a file.
struct Lines<'a>(&'a [u8]);

impl Lines<'_> {
    fn at(&self, offset: usize) -> u32 {
        let end = offset.min(self.0.len());
        let n = self.0[..end].iter().filter(|&&b| b == b'\n').count();
        u32::try_from(n).unwrap_or(u32::MAX).saturating_add(1)
    }

    fn key(&self, table: &dyn TableLike, key: &str) -> Option<u32> {
        let span = table.key(key)?.span()?;
        Some(self.at(span.start))
    }

    fn err(&self, kind: CatalogErrorKind, line: Option<u32>) -> CatalogError {
        CatalogError { kind, line }
    }
}

/// Parses one catalog file. Whether an agent without `name` is new, which
/// is refused, depends on the catalog it joins: [`AgentCatalog::load`]
/// checks. The builtin file names every agent (a test checks it).
fn parse_catalog(bytes: &[u8]) -> Result<CatalogFile, CatalogError> {
    if bytes.len() > MAX_CATALOG_FILE {
        return Err(CatalogErrorKind::TooLarge.into());
    }
    let lines = Lines(bytes);
    let text = std::str::from_utf8(bytes)
        .map_err(|e| lines.err(CatalogErrorKind::NotUtf8, Some(lines.at(e.valid_up_to()))))?;
    let doc = Document::parse(text).map_err(|e| {
        // Classified by its fixed description; the message itself quotes
        // the source and is dropped.
        let kind = if e.message().starts_with("duplicate key") {
            CatalogErrorKind::DuplicateKey
        } else {
            CatalogErrorKind::Syntax
        };
        lines.err(kind, e.span().map(|s| lines.at(s.start)))
    })?;
    let mut file = CatalogFile {
        interpreters: Vec::new(),
        agents: Vec::new(),
    };
    let root = doc.as_table();
    for (key, item) in root.iter() {
        let line = lines.key(root, key);
        match key {
            "interpreters" => {
                for s in strings(&lines, item, line)? {
                    let ok = !s.is_empty()
                        && s.len() <= 64
                        && s != "."
                        && s != ".."
                        && !s.contains(['/', '*'])
                        && !s.chars().any(char::is_control);
                    if !ok {
                        return Err(lines.err(CatalogErrorKind::InvalidInterpreter, line));
                    }
                    file.interpreters.push(s.as_bytes().to_vec());
                }
            }
            "agent" => {
                let Item::ArrayOfTables(tables) = item else {
                    return Err(lines.err(CatalogErrorKind::WrongType, line));
                };
                if tables.len() > MAX_AGENTS_PER_FILE {
                    return Err(lines.err(CatalogErrorKind::TooMany, line));
                }
                for t in tables.iter() {
                    let at = t.span().map(|s| lines.at(s.start)).or(line);
                    let a = agent(&lines, t, at)?;
                    if file.agents.iter().any(|b| b.id == a.id) {
                        return Err(lines.err(CatalogErrorKind::DuplicateId, at));
                    }
                    file.agents.push(a);
                }
            }
            _ => return Err(lines.err(CatalogErrorKind::UnknownKey, line)),
        }
    }
    Ok(file)
}

/// An array of strings, at most [`MAX_LIST`] of them.
fn strings<'a>(
    lines: &Lines<'_>,
    item: &'a Item,
    line: Option<u32>,
) -> Result<Vec<&'a str>, CatalogError> {
    let arr = item
        .as_array()
        .ok_or_else(|| lines.err(CatalogErrorKind::WrongType, line))?;
    if arr.len() > MAX_LIST {
        return Err(lines.err(CatalogErrorKind::TooMany, line));
    }
    arr.iter()
        .map(|v| {
            v.as_str()
                .ok_or_else(|| lines.err(CatalogErrorKind::WrongType, line))
        })
        .collect()
}

fn valid_id(s: &str) -> bool {
    let b = s.as_bytes();
    !b.is_empty()
        && b.len() <= 32
        && b.iter()
            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || *c == b'-')
        && b.first() != Some(&b'-')
        && b.last() != Some(&b'-')
}

/// A 10-character Apple Team ID: uppercase ASCII letters and digits.
fn valid_team(s: &str) -> bool {
    s.len() == 10
        && s.bytes()
            .all(|c| c.is_ascii_uppercase() || c.is_ascii_digit())
}

/// A signing identifier: printable ASCII without spaces, 1 to 128 bytes.
fn valid_identifier(s: &str) -> bool {
    !s.is_empty() && s.len() <= 128 && s.bytes().all(|c| c.is_ascii_graphic())
}

fn agent(
    lines: &Lines<'_>,
    t: &toml_edit::Table,
    at: Option<u32>,
) -> Result<FileAgent, CatalogError> {
    let mut a = FileAgent {
        line: at,
        id: String::new(),
        name: None,
        executables: Vec::new(),
        scripts: Vec::new(),
        signatures: Vec::new(),
        markers: Vec::new(),
    };
    for (key, item) in t.iter() {
        let line = lines.key(t, key).or(at);
        let wrong = || lines.err(CatalogErrorKind::WrongType, line);
        match key {
            "id" => {
                let s = item.as_str().ok_or_else(wrong)?;
                if !valid_id(s) {
                    return Err(lines.err(CatalogErrorKind::InvalidId, line));
                }
                a.id = s.to_owned();
            }
            "name" => {
                let s = item.as_str().ok_or_else(wrong)?;
                if s.len() > MAX_NAME || !valid_project_name(s) {
                    return Err(lines.err(CatalogErrorKind::InvalidName, line));
                }
                a.name = Some(s.to_owned());
            }
            "executables" | "scripts" => {
                let mut v = Vec::new();
                for s in strings(lines, item, line)? {
                    v.push(
                        Pattern::parse(s)
                            .ok_or_else(|| lines.err(CatalogErrorKind::InvalidPattern, line))?,
                    );
                }
                if key == "executables" {
                    a.executables = v;
                } else {
                    a.scripts = v;
                }
            }
            "signatures" => {
                let arr = item.as_array().ok_or_else(wrong)?;
                if arr.len() > MAX_LIST {
                    return Err(lines.err(CatalogErrorKind::TooMany, line));
                }
                for v in arr.iter() {
                    a.signatures.push(signature(lines, v, line)?);
                }
            }
            "markers" => {
                for s in strings(lines, item, line)? {
                    if !EnvName::valid(s.as_bytes()) {
                        return Err(lines.err(CatalogErrorKind::InvalidMarker, line));
                    }
                    a.markers.push(s.to_owned());
                }
            }
            _ => return Err(lines.err(CatalogErrorKind::UnknownKey, line)),
        }
    }
    if a.id.is_empty() {
        return Err(lines.err(CatalogErrorKind::MissingKey, at));
    }
    if a.executables.is_empty()
        && a.scripts.is_empty()
        && a.signatures.is_empty()
        && a.markers.is_empty()
    {
        return Err(lines.err(CatalogErrorKind::EmptyAgent, at));
    }
    Ok(a)
}

fn signature(lines: &Lines<'_>, v: &Value, line: Option<u32>) -> Result<Signature, CatalogError> {
    let invalid = || lines.err(CatalogErrorKind::InvalidSignature, line);
    let t = v.as_inline_table().ok_or_else(invalid)?;
    let mut identifier = None;
    let mut team = None;
    for (key, v) in t.iter() {
        let s = v.as_str().ok_or_else(invalid)?;
        match key {
            "identifier" if valid_identifier(s) => identifier = Some(s.to_owned()),
            "team" if valid_team(s) => team = Some(s.to_owned()),
            _ => return Err(invalid()),
        }
    }
    Ok(Signature {
        identifier: identifier.ok_or_else(invalid)?,
        team,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn patterns_match_path_suffixes() {
        let p = Pattern::parse("claude/versions/*").unwrap();
        assert!(p.matches(b"/home/u/.local/share/claude/versions/2.1.112"));
        assert!(!p.matches(b"/home/u/.local/share/claude/versions"));
        assert!(!p.matches(b"/opt/claude/other/2.1"));
        let p = Pattern::parse("claude").unwrap();
        assert!(p.matches(b"claude"));
        assert!(p.matches(b"./claude"));
        assert!(p.matches(b"/usr/local/bin/claude"));
        assert!(!p.matches(b"/usr/local/bin/claude2"));
        assert!(!p.matches(b"/usr/local/bin/Claude"));
        assert!(!p.matches(b""));
        let p = Pattern::parse("@anthropic-ai/claude-code/cli.js").unwrap();
        assert!(p.matches(b"/opt/lib/node_modules/@anthropic-ai/claude-code/cli.js"));
        assert!(!p.matches(b"/opt/lib/node_modules/@evil/claude-code/cli.js"));
    }

    #[test]
    fn bad_patterns_are_refused() {
        for bad in [
            "", "*", "*/*", "/claude", "claude/", "a//b", "./claude", "a/../b", "cla*de", "a\nb",
        ] {
            assert!(Pattern::parse(bad).is_none(), "{bad:?}");
        }
        assert!(Pattern::parse("a/".repeat(8).trim_end_matches('/')).is_some());
        assert!(Pattern::parse("a/".repeat(9).trim_end_matches('/')).is_none());
        assert!(Pattern::parse(&"a".repeat(257)).is_none());
    }

    #[test]
    fn ids_and_teams() {
        for ok in ["claude-code", "codex", "a", "a1-b2"] {
            assert!(valid_id(ok), "{ok}");
        }
        for bad in ["", "-a", "a-", "A", "a_b", "a b", &"a".repeat(33)] {
            assert!(!valid_id(bad), "{bad}");
        }
        assert!(valid_team("Q6L2SF6YDW"));
        assert!(!valid_team("q6l2sf6ydw"));
        assert!(!valid_team("Q6L2SF6YD"));
    }
}
